### ISSUE TITLE
Google collab version

### ISSUE THREAD

**Issue by shadowzoom** [microsoft/Bringing-Old-Photos-Back-to-Life#1]
Can somebody please make a google collab version please?

**Comment by zhangmozhe** [comment]
Thanks for your suggestion. We have been working on it. Please stay tuned for the update.

**Comment by woctezuma** [comment]
Unless you mean a user inteface, as in [`tg-bomze/StyleGAN2-Face-Modificator`](https://github.com/tg-bomze/StyleGAN2-Face-Modificator), I think you could easily create a Colab notebook by copying the code shown in the README.

**Comment by zhangmozhe** [comment]
Colab demo updated now. Please have a try.
