### ISSUE TITLE
Using CPU instead of CUDA

### ISSUE THREAD

**Issue by jersobh** [microsoft/Bringing-Old-Photos-Back-to-Life#10]
Is it possible to use CPU or even OpenCL instead? CUDA is nvidia proprietary code and I have an AMD laptop. Thanks.

**Comment by zhangmozhe** [comment]
Hi, you can try our Colab demo, which can leverage online GPU for running.

**Comment by perluncha2015** [comment]
So there is no way to use the CPU? Thanks.
