### ISSUE TITLE
module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by orngeatom** [microsoft/Bringing-Old-Photos-Back-to-Life#100]
when executing python run.py --input_folder "XXX" --output_folder "XXX" --GPU 0

the error appears at step one "module 'torch._C' has no attribute '_cuda_setDevice'

- uninstall and reinstall cuda, torch and numpy and verified all is well

- i did try the command with gpu -1 and it does use the cpu but i do have an 3070 with the latest CUDA, cudnn installed ~version 11

**Comment by zhangmozhe** [comment]
Possibly you can refer to this. https://github.com/pytorch/pytorch/issues/33655#issue-569325277
