### ISSUE TITLE
Incorrect output images 

### ISSUE THREAD

**Issue by BiggusCattus** [microsoft/Bringing-Old-Photos-Back-to-Life#101]
I can get the code to run successfully however for the final output the images are all like this

![4girls192332139](https://user-images.githubusercontent.com/67328466/103185258-8ab88500-4889-11eb-8316-773b6b864580.png)

**Comment by BiggusCattus** [comment]
I solved this, it was a pathing issue to the checkpoint directories

**Comment by celikmustafa89** [comment]
same issue, same solution. thank you @BiggusCattus.
to be more informative, I am sharing my error message.

`Mapping: You are using the mapping model without global restoration.
./checkpoints/restoration/VAE_A_quality/latest_net_G.pth not exists yet!
./checkpoints/restoration/VAE_B_quality/latest_net_G.pth not exists yet!
./checkpoints/restoration/mapping_quality/latest_net_mapping_net.pth not exists yet!
Now you are processing a.png
`

**Comment by askme-gpt** [comment]
> same issue, same solution. thank you @BiggusCattus. to be more informative, I am sharing my error message.
> 
> `Mapping: You are using the mapping model without global restoration. ./checkpoints/restoration/VAE_A_quality/latest_net_G.pth not exists yet! ./checkpoints/restoration/VAE_B_quality/latest_net_G.pth not exists yet! ./checkpoints/restoration/mapping_quality/latest_net_mapping_net.pth not exists yet! Now you are processing a.png `

I have the same issue , have you solved it ?
