### ISSUE TITLE
restoration seems not working when scratch is much bigger

### ISSUE THREAD

**Issue by uptodiff** [microsoft/Bringing-Old-Photos-Back-to-Life#102]
I run the code using pretrained weights，finally the result is far away from expectation. Please help me  to figure out whether I run the code using incorrect version of torch or other reason. Thanks very much.
"Origin image"
![image1](https://user-images.githubusercontent.com/17905794/103204886-47b2ec00-4933-11eb-8211-8ee0bc172c1a.jpg)

"result"
![image1](https://user-images.githubusercontent.com/17905794/103205305-36b6aa80-4934-11eb-9eb9-be798294d3a9.png)

**Comment by zhangmozhe** [comment]
Thanks for raising the issue. During training, we did not consider large cracks but focus on small scratches. This is because we have collected very few photos with copyright that contain large crack areas.
