### ISSUE TITLE
How to activate multi-GPU mode?

### ISSUE THREAD

**Issue by Gegam** [microsoft/Bringing-Old-Photos-Back-to-Life#104]
Is the multi-GPU mode supported?  How do I enable it?

Thank you in advance

**Comment by zhangmozhe** [comment]
The test code does not support multi-GPU. The training code supports it. We will release the code soon.

**Comment by HymEric** [comment]
> The test code does not support multi-GPU. The training code supports it. We will release the code soon.

It's a great work. When could you release the training code, please?

**Comment by davaram** [comment]
> 测试代码不支持多GPU。训练代码支持它。我们将尽快发布代码。

so , How to activate multi-GPU mode Now ?
