### ISSUE TITLE
Pretrained Model File Not Found

### ISSUE THREAD

**Issue by mrpassiontea** [microsoft/Bringing-Old-Photos-Back-to-Life#105]
Link to the pretrained model is not found.

**Comment by zhangmozhe** [comment]
Could you please have a try again? There is no problem with the testing on my side.

**Comment by zhangmozhe** [comment]
Please reopen the issue if you still come across the problem.

**Comment by mrpassiontea** [comment]
![image](https://user-images.githubusercontent.com/14931499/103549392-a0155b00-4eea-11eb-8476-48cee0ffede5.png)
I just tried again by clicking on "Pretrained Model" on the readme.md. The link: https://portland-my.sharepoint.com/:f:/g/personal/ziyuwan2-c_ad_cityu_edu_hk/Eh1gtjfLiWtLiBDGZhaTvokBvDUdvA5j49f_NpL_Pp9FPA?e=7EddTf returns not found.
