### ISSUE TITLE
Why doesn't VAE generate mean and variance

### ISSUE THREAD

**Issue by ryanqiutu** [microsoft/Bringing-Old-Photos-Back-to-Life#109]
Why doesn't VAE generate mean and variance? Auto-Encoder or VAE？

**Comment by zhangmozhe** [comment]
> During training, VAE is a must for achieving high-performance quality, which introduces perturbation to the latent space so that the sampling from this continuous space can be mapped to an image. During inference, there is not need to introduce such perturbation, so we just use the centroid of the latent space from which we reconstruct the image. Therefore, the code looks like an autoencoder.
