### ISSUE TITLE
Should the L1 factor 'alpha' be larger?

### ISSUE THREAD

**Issue by HaloKester** [microsoft/Bringing-Old-Photos-Back-to-Life#115]
I reimplement the training code, however, it is hard to increase SSIM to 0.69 when training VAE1 and VAE2 unless I change the L1 factor 'alpha'. I would like to know that how long did it take you to train VAE1 and VAE2? Would you tell me the rough time about releasing training code?

**Comment by wytcsuch** [comment]
> I reimplement the training code, however, it is hard to increase SSIM to 0.69 when training VAE1 and VAE2 unless I change the L1 factor 'alpha'. I would like to know that how long did it take you to train VAE1 and VAE2? Would you tell me the rough time about releasing training code?

I also reimplement the training code,and I change the L1 factor 'alpha' to 10000

**Comment by HaloKester** [comment]
> > I reimplement the training code, however, it is hard to increase SSIM to 0.69 when training VAE1 and VAE2 unless I change the L1 factor 'alpha'. I would like to know that how long did it take you to train VAE1 and VAE2? Would you tell me the rough time about releasing training code?
> 
> I also reimplement the training code,and I change the L1 factor 'alpha' to 10000

It can increase SSIM but I am worrying about the factor 'alpha' may reduce the influence of other loss, such as kld_loss and adv_loss.
Have you acquired satisfied results?

**Comment by wytcsuch** [comment]
> > > I reimplement the training code, however, it is hard to increase SSIM to 0.69 when training VAE1 and VAE2 unless I change the L1 factor 'alpha'. I would like to know that how long did it take you to train VAE1 and VAE2? Would you tell me the rough time about releasing training code?
> > 
> > 
> > I also reimplement the training code,and I change the L1 factor 'alpha' to 10000
> 
> It can increase SSIM but I am worrying about the factor 'alpha' may reduce the influence of other loss, such as kld_loss and adv_loss.
> Have you acquired satisfied results?

![图片](https://user-images.githubusercontent.com/40099267/106984556-d15fa000-67a2-11eb-8d60-222ed9ce29d3.png)
The second line is the reconstructed the image

**Comment by wytcsuch** [comment]
My latent space is 64 × 32 × 32, and the temperature in training is 0.7

**Comment by HaloKester** [comment]
It encourages me to continue improving at this direction! And I have other questions:
1. How long did it take to train for this result?
2. Have you try to joint training two VAE and one MAPPING？Enhancing L1 Loss may weaken other Loss that make the domain of 'r' hard to converge to the domain of 'x'?

**Comment by wytcsuch** [comment]
> It encourages me to continue improving at this direction! And I have other questions:
> 
> 1. How long did it take to train for this result?
> 2. Have you try to joint training two VAE and one MAPPING？Enhancing L1 Loss may weaken other Loss that make the domain of 'r' hard to converge to the domain of 'x'?

1. one day on 2080ti
2. My training method is to train VAE A and VAE B separately, and then joint train the mapping net and face enhancement

**Comment by HaloKester** [comment]
Okay, thanks~

**Comment by syfbme** [comment]
Hi @HaloKester @wytcsuch 
Thanks for the information above. I have 2 questions:

1. What's the resolution of your input images?
2. Could you please kindly share your training code.(Email: 15267028249@163.com)
Thanks.

**Comment by zhangmozhe** [comment]
Training code is just added. Welcome to go through it and learn the training details.
