### ISSUE TITLE
nn. Pytorch error

### ISSUE THREAD

**Issue by Zudva** [microsoft/Bringing-Old-Photos-Back-to-Life#116]
Traceback (most recent call last):
  File "detection.py", line 156, in <module>
    main(config)
  File "detection.py", line 128, in main
    P = torch.sigmoid(model(scratch_image))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/photo_restoration/Global/detection_models/networks.py", line 110, in forward
    x = self.first(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
You are using NL + Res

**Comment by Terrored** [comment]
Same for me. Any idea what's going on?

**Comment by phadytou** [comment]
Thank you so much

**Comment by phadytou** [comment]
> Traceback (most recent call last):
> 
>   File "detection.py", line 156, in <module>
> 
>     main(config)
> 
>   File "detection.py", line 128, in main
> 
>     P = torch.sigmoid(model(scratch_image))
> 
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> 
>     result = self.forward(*input, **kwargs)
> 
>   File "/content/photo_restoration/Global/detection_models/networks.py", line 110, in forward
> 
>     x = self.first(x)
> 
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> 
>     result = self.forward(*input, **kwargs)
> 
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
> 
>     input = module(input)
> 
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> 
>     result = self.forward(*input, **kwargs)
> 
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 423, in forward
> 
>     return self._conv_forward(input, self.weight)
> 
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
> 
>     self.padding, self.dilation, self.groups)
> 
> RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
> 
> You are using NL + Res

**Comment by zhangmozhe** [comment]
> Traceback (most recent call last):
> File "detection.py", line 156, in
> main(config)
> File "detection.py", line 128, in main
> P = torch.sigmoid(model(scratch_image))
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/content/photo_restoration/Global/detection_models/networks.py", line 110, in forward
> x = self.first(x)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
> input = module(input)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 423, in forward
> return self._conv_forward(input, self.weight)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
> You are using NL + Res

I do not have problems when running `python run.py --input_folder test_images/old_w_scratch --output_folder output  --GPU 0 --with_scratch`. Could you please post your running command or share a colab link so that we can reproduce the error?

**Comment by phadytou** [comment]
I need you let me go if you not love me
