### ISSUE TITLE
So happy to see the recent update, and still hope to see the training code, especially training vae

### ISSUE THREAD

**Issue by vegetable09** [microsoft/Bringing-Old-Photos-Back-to-Life#118]
I'm happy to see @zhangmozhe just updated this repo some days ago.

And this raise my hope for the release of the training code again. I'm hard to reproduce the same result since the D net is not provided yet.

Thanks for @zhangmozhe and other maintainers

**Comment by zhangmozhe** [comment]
Training code is just added. Welcome to have a try. Thanks.
