### ISSUE TITLE
Absolute path not found

### ISSUE THREAD

**Issue by g14a** [microsoft/Bringing-Old-Photos-Back-to-Life#12]
I setup everything successfully using pip3 and I run this with a test image in the `test_image` folder on my desktop.
```
python run.py --input_folder /Users/g14a/Desktop/test_image/ --output_folder /Users/g14a/Desktop/test_output/ --GPU 0 --with_scratch
```

 and then I get this error log.

```
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "detection.py", line 9, in <module>
    import torch
ImportError: No module named torch
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch.autograd import Variable
ImportError: No module named torch.autograd
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    for x in os.listdir(stage_1_results):
OSError: [Errno 2] No such file or directory: '/Users/g14a/Desktop/test_output/stage_1_restore_output/restored_image'
```

Is there anything I'm missing here?

**Comment by raywzy** [comment]
Yes. You need to install the PyTorch according to your cuda version in advance.

**Comment by bjwest** [comment]
It would've been nice to know this required an Nvidia GPU before I took the time to install.  Nowhere in the README.md or in the document on Google drive does it mention that.

**Comment by g14a** [comment]
> It would've been nice to know this required an Nvidia GPU before I took the time to install. Nowhere in the README.md or in the document on Google drive does it mention that.

Exactly. I have an AMD Radeon and I had no clue about it.
