### ISSUE TITLE
File not found error of "Pretrained Model" Link

### ISSUE THREAD

**Issue by rptxk01** [microsoft/Bringing-Old-Photos-Back-to-Life#120]
I tried to download pretrained weight by clicking on "Pretrained Model" on the readme.md. 
It returns not found page.

https://portland-my.sharepoint.com/:f:/g/personal/ziyuwan2-c_ad_cityu_edu_hk/Eh1gtjfLiWtLiBDGZhaTvokBvDUdvA5j49f_NpL_Pp9FPA?e=7EddTf

**Comment by zhangmozhe** [comment]
Thanks for your feedback. The link is fixed. Or you can download the pre-trained model from Azure blob by：

```
cd Face_Enhancement/
wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Face_Enhancement/checkpoints.zip
unzip checkpoints.zip
cd ../
cd Global/
wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Global/checkpoints.zip
unzip checkpoints.zip
cd ../
```
