### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by ricardoborges** [microsoft/Bringing-Old-Photos-Back-to-Life#122]
Hey guys,

I got that error, do you know how can I fix it?

Running Stage 2: Face Detection
Traceback (most recent call last):
  File "detect_all_dlib.py", line 19, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Finish Stage 2 ...

Running Stage 4: Blending
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 18, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Finish Stage 4 ...

**Comment by ricardoborges** [comment]
I'm trying "--GPU -1"

**Comment by ricardoborges** [comment]
I've got erros on pip installing requirements

**Comment by syfbme** [comment]
Have you installed opencv in your enviroment

**Comment by Jak0917377107** [comment]
[](about:blank)

**Comment by Jak0917377107** [comment]
about:blank

**Comment by zhangmozhe** [comment]
Can you please attach more information about the pip install requirements?
