### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by ricardoborges** [microsoft/Bringing-Old-Photos-Back-to-Life#123]
I'm trying to run on Ubuntu with NVidia. I installed CUDA as the tutorial said. Any clue?

**Comment by zhangmozhe** [comment]
Please install the cuda using the tutorial like: https://patrickorcl.medium.com/install-cuda-10-and-cudnn-on-ubuntu-18-b28b59bae279. Or you can run the code on CPU with the command line option "--GPU 0".
