### ISSUE TITLE
Hey team! I had tired to install all your cool stuff to pure VM and created simple ansible playbook. Take a look please, maybe it would be useful .

### ISSUE THREAD

**Issue by Jak0917377107** [microsoft/Bringing-Old-Photos-Back-to-Life#124]
Hey team! I had tired to install all your cool stuff to pure VM and created simple ansible playbook. Take a look please, maybe it would be useful . 

__Originally posted by @codeandmedia in https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/pull/117__

**Comment by zhangmozhe** [comment]
Thanks for your contribution! We've merged the code into the project.
