### ISSUE TITLE
processing p001.TIF You are using NL + Res Now you are processing p001.png Skip p001.png due to an error: CUDA out of memory. Tried to allocate 99.40 GiB (GPU 0; 8.00 GiB total capacity; 3.24 GiB already allocated; 728.64 MiB free; 5.79 GiB reserved in total by PyTorch) Finish Stage 1 ...

### ISSUE THREAD

**Issue by ZevFung** [microsoft/Bringing-Old-Photos-Back-to-Life#127]
processing p001.TIF
You are using NL + Res
Now you are processing p001.png
Skip p001.png due to an error:
CUDA out of memory. Tried to allocate 99.40 GiB (GPU 0; 8.00 GiB total capacity; 3.24 GiB already allocated; 728.64 MiB free; 5.79 GiB reserved in total by PyTorch)
Finish Stage 1 ...

**Comment by zhangmozhe** [comment]
Please refer to https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/128#issuecomment-809042636
