### ISSUE TITLE
[enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

### ISSUE THREAD

**Issue by boxter007** [microsoft/Bringing-Old-Photos-Back-to-Life#129]
# python3 run.py --input_folder /mnt/d/old/ --output_folder /mnt/d/new/ --GPU -1 --with_scratch
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
directory of testing image: /mnt/d/old
processing IMG_0233.JPG
You are using NL + Res
Now you are processing IMG_0233.png
Skip IMG_0233.png due to an error:
[enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

**Comment by zhangmozhe** [comment]
According to https://discuss.pytorch.org/t/pytorch-runtimeerror-enforce-fail-at-cpuallocator-cpp-56-posix-memalign-data-galignment-nbytes-0-12-vs-0/46072/3, you are facing out of memory error. Please try to resize the input photo size a little bit and try again.
