### ISSUE TITLE
About the error of installing dlib package

### ISSUE THREAD

**Issue by love112358** [microsoft/Bringing-Old-Photos-Back-to-Life#133]
When I installed dlib  package in requirements.txt through pip, the following error occurred. I would like to ask why and how to solve this problem. Thank you
![image](https://user-images.githubusercontent.com/33959491/113103706-33cc9e00-9232-11eb-9682-2dde70938a0f.png)
![image](https://user-images.githubusercontent.com/33959491/113103749-42b35080-9232-11eb-879a-81098d06f6bb.png)
![image](https://user-images.githubusercontent.com/33959491/113103806-52cb3000-9232-11eb-84c2-9d36892ab8cf.png)
![image](https://user-images.githubusercontent.com/33959491/113103892-6ffffe80-9232-11eb-80f5-8d7f2516c98a.png)
![image](https://user-images.githubusercontent.com/33959491/113103961-83ab6500-9232-11eb-81fe-802dfb67cb1e.png)

**Comment by mahesh557** [comment]
Install CMAKE, Visual Studio (CMAKE C++ Compiler along with Windows 10 SDK)
Then do pip3 install wheels followed by pip3 install dlib
https://medium.com/analytics-vidhya/how-to-install-dlib-library-for-python-in-windows-10-57348ba1117f

If Windows 10 SDK is not present it will throw out all kinds of errors like above
