### ISSUE TITLE
The training codes of face enhancement

### ISSUE THREAD

**Issue by reason4** [microsoft/Bringing-Old-Photos-Back-to-Life#134]
Thanks for releasing the training codes!

The training codes of face enhancement seems not to be released. Do you plan to release it?

 Look forward to your reply！

**Comment by raywzy** [comment]
Yes. We will release the face refinement part in the future.

**Comment by reason4** [comment]
> Yes. We will release the face refinement part in the future.

**Comment by reason4** [comment]
Do you have any plan when will it be released? Thanks!
