### ISSUE TITLE
It seems that reconstruction loss is not used in training VAE

### ISSUE THREAD

**Issue by wytcsuch** [microsoft/Bringing-Old-Photos-Back-to-Life#135]
I have been looking forward to the official training code, thank you very much for your contribution.I understand that opt.Smooth_L1 means whether to use reconstruction loss. opt.Smooth_L1is False in training instruction. I wonder why reconstruction loss was not adopted
`self.loss_filter = self.init_loss_filter(not opt.no_ganFeat_loss, not opt.no_vgg_loss, opt.Smooth_L1)`

**Comment by raywzy** [comment]
Hi,
We adopt the VGG feature matching loss as reconstruction guidance. You could also try the smooth L1 :)
