### ISSUE TITLE
Confused with piece of code in Loss

### ISSUE THREAD

**Issue by syfbme** [microsoft/Bringing-Old-Photos-Back-to-Life#136]
In file pix2pixHD_model_DA.py:
pred_fake_feat=self.feat_discriminate(real_old_feat)
Why use real_old_feat to calculate pred_fake_feat?
If we want to make featD stronger, we should use below code instead:
pred_fake_feat=self.feat_discriminate(syn_feat)

Please help. Thanks.

loss_G_featD has the same situation

**Comment by raywzy** [comment]
It's an adversarial procedure to narrow down the distribution gap between syn degradation feature and natural degradation feature. No extra constraints are posed here to define which domain is real or fake.

**Comment by syfbme** [comment]
Sorry, i still don't get it. Here is my understanding when following your code:
Use featD_fake and featD_real, we will get a featD which discriminates a real old photo as a synthetic photo and discriminates a synthetic photo as a real old photo. Ideally, we will get a featD which is unable to discriminate these two kinds of photo. I think this is what you mean "narrow down the distribution gap between syn degradation feature and natural degradation feature". Then we use this featD to adversarially train VAE's encoder. We want VAE's encoder generate a "true" latent space code using real old photo. But we have a featD which can't discriminate real and synthetic. How does this featD help VAE's encoder.
I am really confused. Please correct me. Thanks in advance.

**Comment by syfbme** [comment]
Hi @raywzy @zhangmozhe 
Looking forward to your reply. Thanks.

**Comment by syfbme** [comment]
I finally got it...
G: 1-D(real)
featD: D(real)
It truly is an adversarial procedure. But it is different from general GAN. Maybe it is better to let G see more real old photos
