### ISSUE TITLE
Can't resolve facevc.blob.core.windows.net

### ISSUE THREAD

**Issue by alex4u2nv** [microsoft/Bringing-Old-Photos-Back-to-Life#139]
```
wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Face_Enhancement/checkpoints.zip
--2021-04-01 17:52:22--  https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Face_Enhancement/checkpoints.zip
Resolving facevc.blob.core.windows.net (facevc.blob.core.windows.net)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘facevc.blob.core.windows.net’
```

When running `curl`, `wget`, or `browser` to access this artifact, it seems to not resolve the host. 
It looks like the DNS may no longer be working?
https://dnschecker.org/#A/facev.blob.core.windows.net
![Screen Shot 2021-04-01 at 5 57 55 PM](https://user-images.githubusercontent.com/40564/113358447-d14bce80-9313-11eb-915a-f72f0f1c5395.png)

**Comment by zhangmozhe** [comment]
Hi, I tested with Colab and my local computer, but do not have the error.

![image](https://user-images.githubusercontent.com/10203551/113384895-9d2ae900-93b9-11eb-854b-b0485516b0e6.png)

**Comment by alex4u2nv** [comment]
Thanks for looking into it @zhangmozhe . It looks like the resources is back online. I'll close the ticket
