### ISSUE TITLE
Out of Memory for Global Restoration

### ISSUE THREAD

**Issue by mahesh557** [microsoft/Bringing-Old-Photos-Back-to-Life#140]
Hi,

I am running on Intel i7 with 16GB RAM
Even with 16 GB it is throwing below error while processing 1180 * 768 image

```
D:\photo_restoration\Global>python test.py --Scratch_and_Quality_restore --test_input input --test_mask output\mask --outputs_dir output --gpu_ids -1
You are using NL + Res
Now you are processing old.jpg
Skip old.jpg due to an error:
[enforce fail at ..\c10\core\CPUAllocator.cpp:75] data. DefaultCPUAllocator: not enough memory: you tried to allocate 12919504896 bytes. Buy new RAM!
```

**Comment by raywzy** [comment]
Hi, 
currently the model could not support large size input with scratches. One solution is to resize the input image. Meanwhile we are trying to improve this aspect.

**Comment by zhangmozhe** [comment]
Hello, we just redesign the network to support high-resolution images. Welcome to have a try. You can run the code with arguments:

python run.py --input_folder [test_image_folder_path] \
              --output_folder [output_path] \
              --GPU 0 \
              --with_scratch \
              --HR
