### ISSUE TITLE
Real_L_old and Real_RGB_old

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [microsoft/Bringing-Old-Photos-Back-to-Life#142]
Hi thank you so much for sharing this greate work! I'm just shocked on how it works on those wild old photos, it's just amazing

However when I tried to follow the instructions on the training process, I'm confused preparing the dataset. 
My question is that what's the difference between Real_L_old and Real_RGB_old? 
According to the paper, I think we only need VOC images, synthesised degraded VOC images and real old photos (Real_RGB_old perhaps?)

So what is this Real_L_old ?

**Comment by syfbme** [comment]
Real_L_old stands for gray old image which has only one channel while real_rgb_old has 3 channel rgb

**Comment by raywzy** [comment]
You could modify here via fetching data from one source file if the colleceded data are mixed together.

**Comment by MengXinChengXuYuan** [comment]
I see!
Thank you so mush for the quick response
Again your work is just amazing!!!

**Comment by Mr-doraemon** [comment]
> 
> 
> Hi thank you so much for sharing this greate work! I'm just shocked on how it works on those wild old photos, it's just amazing
> 
> However when I tried to follow the instructions on the training process, I'm confused preparing the dataset.
> My question is that what's the difference between Real_L_old and Real_RGB_old?
> According to the paper, I think we only need VOC images, synthesised degraded VOC images and real old photos (Real_RGB_old perhaps?)
> 
> So what is this Real_L_old ?

Hello, I am following this work recently, and I am not clear about the organizational form of the data, could you please explain it in detail? How do I get VOC degraded images and grayscale images of the real old photos? Thank you
