### ISSUE TITLE
AttributeError: 'Pix2PixHDModel' object has no attribute 'module'

### ISSUE THREAD

**Issue by AliceNotebook** [microsoft/Bringing-Old-Photos-Back-to-Life#147]
when running train_domain_A.py or train_domain_B.py

**Comment by Mr-doraemon** [comment]
I had the same problem. Did you solve it

**Comment by AliceNotebook** [comment]
> I had the same problem. Did you solve it

could you tell me how to solve it?
delete modle.moudle.xxx and use model.xxx?

**Comment by raywzy** [comment]
The training process are on multiple GPUs by default. Removing the "moudle" is okay.
