### ISSUE TITLE
~~~~~ No such file or directory ~~~~~ 

### ISSUE THREAD

**Issue by AlexMTM** [microsoft/Bringing-Old-Photos-Back-to-Life#148]
can someone help? first of all, I would like to record that I am a layman with this! so... I installed the files as taught in the tutorial and the installation was successful! now i'm trying to run the first test step but i always have this error reported! I know it’s my fault, but I don’t know where. Because I am indicating the location of the files and I get this error! I appreciate if someone identifies my fault so I can fix it !!! And as for the gpu command, I did not put it on purpose because I want to run it with my cpu, and when I use -1 as informed in the tutorial, I get a message saying that this command does not exist.....

```

alex@ubuntu:~/Downloads/Bringing-Old-Photos-Back-to-Life-master$ python run.py --input_folder [test_images] \
> --output_folder [output_path] 
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch.autograd import Variable
ImportError: No module named torch.autograd
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    for x in os.listdir(stage_1_results):
OSError: [Errno 2] No such file or directory: '/home/alex/Downloads/Bringing-Old-Photos-Back-to-Life-master/[output_path]/stage_1_restore_output/restored_image'
alex@ubuntu:~/Downloads/Bringing-Old-Photos-Back-to-Life-master$ 
```

**Comment by normanade** [comment]
Clearly you should set your input & output folder instead of `[test_images]` & `[output_path]`. Changing them into valid paths should do the job for you.

**Comment by AlexMTM** [comment]
> Clearly you should set your input & output folder instead of `[test_images]` & `[output_path]`. Changing them into valid paths should do the job for you.
