### ISSUE TITLE
What's the ratio of each losses when training mapping T

### ISSUE THREAD

**Issue by syfbme** [microsoft/Bringing-Old-Photos-Back-to-Life#149]
In my case, the G_Feat_L2(lambda=60) is much larger than  other loss  with your script. Below is the first 1200 iters:
(epoch: 1, iters: 24, time: 1.745 lr: 0.00020) G_Feat_L2: 71.198 G_GAN: 6.186 G_GAN_Feat: 15.838 G_VGG: 11.113 D_real: 6.164 D_fake: 5.030 
(epoch: 1, iters: 600, time: 0.069 lr: 0.00020) G_Feat_L2: 66.881 G_GAN: 12.149 G_GAN_Feat: 12.813 G_VGG: 10.724 D_real: 10.091 D_fake: 11.878 
(epoch: 1, iters: 1200, time: 0.068 lr: 0.00020) G_Feat_L2: 65.914 G_GAN: 4.420 G_GAN_Feat: 8.283 G_VGG: 9.541 D_real: 4.062 D_fake: 4.153 

Maybe i should lower the number of l2_feat to make all losses at the same level?

**Comment by raywzy** [comment]
Yes, you could try to lower down the weights of feature-level loss, but it won't matter a lot in my experience.

**Comment by syfbme** [comment]
Thanks for your reply. I have tried to lower the rate to 12 in order to make all losses at the same level. But it doesn't matter a lot as you said.
