### ISSUE TITLE
Windows users FileNotFoundError: [Errno 2] During Running Stage 4: Blending

### ISSUE THREAD

**Issue by pyrator** [microsoft/Bringing-Old-Photos-Back-to-Life#15]
If you encounter the above error you will probably need to change one line of code in Face_Enhancement\test_face.py
Currently line 40 reads 
`img_name = img_path[b].split("/")[-1]`
Change this to
`img_name = img_path[b].split("\\")[-1]`

**Comment by hjinlee88** [comment]
i think that should be
`img_name = os.path.split(img_path[b])[-1]`

**Comment by zhangmozhe** [comment]
Thanks! Already fix the issue according to the suggestion.
