### ISSUE TITLE
organizational form of the VOC、Real_L_old and Real_RGB_old

### ISSUE THREAD

**Issue by Mr-doraemon** [microsoft/Bringing-Old-Photos-Back-to-Life#150]
Hello, I am following this work recently, and I am not clear about the organizational form of the data, could you please explain it in detail? How do I get VOC degraded images and grayscale images of the real old photos? Thank you

**Comment by normanade** [comment]
Seems that the data used in training aren't officially released, and all that released are the code of the model and the code for training (Recently added about twenty days before).

There used to be a link in [the project's site](http://raywzy.com/Old_Photo/) pointing to the `dataset`, however it is canceled for certain unknown reasons.
