### ISSUE TITLE
The models are not updated when training the mapping model

### ISSUE THREAD

**Issue by AliceNotebook** [microsoft/Bringing-Old-Photos-Back-to-Life#154]
when running training_mapping.py,it showed the models were saved at the end of epoch.
but the pretrained model were not updated and i can't find the updated models in checkpoints_dir.

**Comment by Darren-dagong** [comment]
> > 运行training_mapping.py时，它显示模型在epoch结束时保存。但是预训练模型没有更新，我在 checkpoints_dir 中找不到更新的模型。
> 
> 我也是，你的问题解决了吗？

so i do, have you solved the problem?

**Comment by Darren-dagong** [comment]
> > when running training_mapping.py,it showed the models were saved at the end of epoch. but the pretrained model were not updated and i can't find the updated models in checkpoints_dir.
> 
> So do i, did you solve the problem yet?

**Comment by Ssakura-go** [comment]
> epoch. but the pretrained model were not updated and i can't find the updated models in checkpoints_dir.

Thanks for your reply! I had solve my problem recently. There is exactly a different between the source code and my running-well code.
