### ISSUE TITLE
Resize or Crop when training large photo

### ISSUE THREAD

**Issue by syfbme** [microsoft/Bringing-Old-Photos-Back-to-Life#156]
What do you suggest? Or just try both ways and see. Looking forward to your reply

**Comment by Aayush-hub** [comment]
@syfbme How we can handle correct aspect ratio of images if we resize them?

**Comment by syfbme** [comment]
> @syfbme How we can handle correct aspect ratio of images if we resize them?

Resize while keep original aspect ratio

**Comment by Aayush-hub** [comment]
> > @syfbme How we can handle correct aspect ratio of images if we resize them?
> 
> Resize while keep original aspect ratio

@syfbme don't you think taking size of image, resizing it to its aspect ratios and then processing it will increase the overall time of execution of program?
@zhangmozhe  Can we take a maximum aspect ratio possible, which I researched is about 600x421px possible with this program  as it is binding by maximum RAM usage to resize large images?

**Comment by zhangmozhe** [comment]
Hello, we just redesign the network to support high-resolution images. Welcome to have a try. You can run the code with arguments:

python run.py --input_folder [test_image_folder_path] \
              --output_folder [output_path] \
              --GPU 0 \
              --with_scratch \
              --HR

**Comment by syfbme** [comment]
> Hello, we just redesign the network to support high-resolution images. Welcome to have a try. You can run the code with arguments:
> 
> python run.py --input_folder [test_image_folder_path]
> --output_folder [output_path]
> --GPU 0
> --with_scratch
> --HR

Hi @zhangmozhe  Thanks for the release. I wonder if there is a model supporting hr images without scratch. Do you plan to release such a model or  how can i train the current code to get such a model
