### ISSUE TITLE
Make frontend for the project

### ISSUE THREAD

**Issue by Aayush-hub** [microsoft/Bringing-Old-Photos-Back-to-Life#159]
Make a interactive frontend for the project `Bringing Old Photos Back` , where the user can upload photo or click it by camera and then can download the result image and share it.

**Comment by Aayush-hub** [comment]
@zhangmozhe I am Working on it!!

**Comment by zhangmozhe** [comment]
That's a great idea. Which python library do you use for the GUI?

**Comment by Aayush-hub** [comment]
@zhangmozhe Can use Python-Flask for frontend!

**Comment by zhangmozhe** [comment]
That's great. Thanks for your contribution, and please let us know once you have progress. Look forward to the beautiful GUI.

**Comment by Aayush-hub** [comment]
@zhangmozhe Sure, will share the progress! Thank you for approving this!

**Comment by Aayush-hub** [comment]
@zhangmozhe I think there is bug in code, in networks>normalization.py `from models.networks.sync_batchnorm import SynchronizedBatchNorm2d` this is imported but there is no such thing exists, its also giving error there.
![1](https://user-images.githubusercontent.com/65889104/118153557-aa64da00-b433-11eb-9376-70a87225253b.PNG)

error!
![2](https://user-images.githubusercontent.com/65889104/118154000-252df500-b434-11eb-8c62-3cfed796a424.PNG)

**Comment by Aayush-hub** [comment]
@zhangmozhe Can I get help with this, I am getting error after latest update. I have made some UI but when I tried running code I am getting this error. I have followed every step in Readme, and ran them successfully. I am running them as default, just changing GPU flag to -1 for CPU.

![1](https://user-images.githubusercontent.com/65889104/118289201-b8c5fb00-b4f2-11eb-95e8-381db6eef796.PNG)

**Comment by Aayush-hub** [comment]
@zhangmozhe Ping! Still getting this error, can you please help?

**Comment by zhangmozhe** [comment]
@raywzy Could you help to address the issue?

**Comment by syfbme** [comment]
> @zhangmozhe Can I get help with this, I am getting error after latest update. I have made some UI but when I tried running code I am getting this error. I have followed every step in Readme, and ran them successfully. I am running them as default, just changing GPU flag to -1 for CPU.
> 
> ![1](https://user-images.githubusercontent.com/65889104/118289201-b8c5fb00-b4f2-11eb-95e8-381db6eef796.PNG)

According to the screenshot, you should use "--gpu_ids" instead of "--GPU".

**Comment by Aayush-hub** [comment]
> > @zhangmozhe Can I get help with this, I am getting error after latest update. I have made some UI but when I tried running code I am getting this error. I have followed every step in Readme, and ran them successfully. I am running them as default, just changing GPU flag to -1 for CPU.
> > ![1](https://user-images.githubusercontent.com/65889104/118289201-b8c5fb00-b4f2-11eb-95e8-381db6eef796.PNG)
> 
> According to the screenshot, you should use "--gpu_ids" instead of "--GPU".

Basically the problem is coming with output folder path in test.py , and the parsers are defined within code and for gpu it's --GPU and then the GPU id. Also one thing to mention if I am trying to run everything default by `python run.py` then also its giving me same error.

@zhangmozhe @raywzy Can you please help, tried very very hard, getting same error after recent updates in the code. Can you please check the code in any cpu machine, and let me know if I am missing something!

**Comment by raywzy** [comment]
> > > @zhangmozhe Can I get help with this, I am getting error after latest update. I have made some UI but when I tried running code I am getting this error. I have followed every step in Readme, and ran them successfully. I am running them as default, just changing GPU flag to -1 for CPU.
> > > ![1](https://user-images.githubusercontent.com/65889104/118289201-b8c5fb00-b4f2-11eb-95e8-381db6eef796.PNG)
> > 
> > 
> > According to the screenshot, you should use "--gpu_ids" instead of "--GPU".
> 
> Basically the problem is coming with output folder path in test.py , and the parsers are defined within code and for gpu it's --GPU and then the GPU id. Also one thing to mention if I am trying to run everything default by `python run.py` then also its giving me same error.
> 
> @zhangmozhe @raywzy Can you please help, tried very very hard, getting same error after recent updates in the code. Can you please check the code in any cpu machine, and let me know if I am missing something!

Hi, thanks for your contribution! Could you please try to change the folder name "photos back to life" to "photos_back_to_life"? It seems the problems come from the unexpected blank space of parsing.
