### ISSUE TITLE
Put weights in a github release to allow automated downloads

### ISSUE THREAD

**Issue by Nintorac** [microsoft/Bringing-Old-Photos-Back-to-Life#16]
Hey,

Setup may be a bit easier if you didn't have to manually download weights. This can be done through Github releases

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-releases

This allows you to attach multiple files and each file has a 2gb filesize limit so the models in here fit in that!

Cheers

**Comment by zhangmozhe** [comment]
Thanks for your suggestion. We have put the pretrained weight to Azure Storage. The files can be easily downloaded with wget.
