### ISSUE TITLE
why IN instead of BN?

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [microsoft/Bringing-Old-Photos-Back-to-Life#160]
Could anyone explain me why use IN instead of BN？
In my opinion, if there are no relation between samples, like stylegan generating individual human faces, styletransfer or image to image translation with individual content, there is no obivious relation between samples.
But as for old photo restoration, I think there is relation between samples, like denoise\remove similar scraches, they have something in common.
So I think BN maybe better?

**Comment by p1x31** [comment]
When training with a low batch size it is very likely to experience inaccurate batch statistics estimation. Therefore other normalization methods are preferred to be used like Group norm, Layer norm or IN. Please refer to this [paper](https://arxiv.org/pdf/1803.08494.pdf). For this reason, within topologies such as ESRGAN BN layers have been removed. For example, you can observe BN artifacts occasionally appear in this [project](https://github.com/IBM/MAX-Image-Resolution-Enhancer) or stock SRGAN. Hope this answers your question.
