### ISSUE TITLE
What Library Versions are used with this project?

### ISSUE THREAD

**Issue by jDavidnet** [microsoft/Bringing-Old-Photos-Back-to-Life#168]
I have been playing with this code for a number of months and I have been having memory issues with it.  What library versions was it tested with?

- What version of TensorFlow?
- What version of Cuda Toolkit?
- What version of cudnn?
- What version of PyTorch?

**Comment by p1x31** [comment]
Hi, you may experience VRAM or RAM issues for large images. The only crucial requirement to run the code is Python>=3.6. You can install the latest versions in requirements.txt. Here is the list of library versions I've tested. Works like a charm.
tensorboardx        2.1 
torch                     1.7.1+cu110              
torchsummary      1.5.1                  
torchvision            0.8.2+cu110 
cudatoolkit            11.0.221
