### ISSUE TITLE
Have you tried k_size=3?

### ISSUE THREAD

**Issue by syfbme** [microsoft/Bringing-Old-Photos-Back-to-Life#169]
I wonder why you use k_size=4? Have you tried k_size=3 and found that k_size=4 is the better one?
Use k_size=4 to avoid checkboard artifact?

**Comment by raywzy** [comment]
Hi, thanks for your suggestion. Actually I didn't tune the parameter very carefully. Maybe your attempt will be better :)

**Comment by syfbme** [comment]
Thanks for your reply~
