### ISSUE TITLE
No such file or directory: output/stage_1_restore_output/restored_image

### ISSUE THREAD

**Issue by dpnchl** [microsoft/Bringing-Old-Photos-Back-to-Life#17]
Need to manually create the restored_image dir otherwise the following failure occurs:

```
$ python run.py --input_folder ~/Documents/revive-old-photos/input --output ~/Documents/revive-old-photos/output --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch.autograd import Variable
ImportError: No module named torch.autograd
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/revive-old-photos/output/stage_1_restore_output/restored_image'
```

**Comment by viklen30** [comment]
(base) PS E:\vvv> python run.py --input_folder ~\vvv\test_images/input --output ~\home\jingliao\ziyuwan\workspace\codes\PAMI\outputs/ --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    input_loader = os.listdir(opt.test_input)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '~\\vvv\\test_images/input'
Finish Stage 1 ...

**Comment by mewbot97** [comment]
i get the exact same error. Im running python 2.7.x even when I just type "python import torch" i get the same error.

**Comment by mewbot97** [comment]
i changed to python3 and it works now. ull have to change some hardcoded python to python3.

**Comment by dpnchl** [comment]
torch should be added to the requirements.txt file to resolve this issue

**Comment by Lauriy** [comment]
Had to:
`pip install torchvision`
and make that missing restored_image directory.

**Comment by GarrettBeatty** [comment]
I had to use a virtual env to make it work

```
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

**Comment by fant59** [comment]
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from Global.options.test_options import TestOptions
ModuleNotFoundError: No module named 'Global'
```
I fixed all libs and modules, when we imported it's, but I get this error again and again. 
Before, I'm download project – install and it's not work ☹️☹️☹️

What am I doing wrong?

**Comment by GarrettBeatty** [comment]
Are you running it from the right directory?

```
git clone https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life.git
cd Bringing-Old-Photos-Back-to-Life
python3 -m venv .venv


cd Face_Enhancement/models/networks/
git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch
cp -rf Synchronized-BatchNorm-PyTorch/sync_batchnorm .
cd ../../../

cd Global/detection_models
git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch
cp -rf Synchronized-BatchNorm-PyTorch/sync_batchnorm .
cd ../../

cd Face_Detection/
wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
bzip2 -d shape_predictor_68_face_landmarks.dat.bz2
cd ../

cd Face_Enhancement/
wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Face_Enhancement/checkpoints.zip
unzip checkpoints.zip
cd ../
cd Global/
wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Global/checkpoints.zip
unzip checkpoints.zip
cd ../

#try pip3 if below doesnt work
pip install -r requirements.txt

#try python3 if below doesnt work
python run.py --input_folder [test_image_folder_path] \
              --output_folder [output_path] \
              --GPU 0

**Comment by fant59** [comment]
Of course 😊

This is my dir where the project is located.

![image](https://user-images.githubusercontent.com/40704315/95832482-f9824980-0d42-11eb-90f2-d057a2c2f6ba.png)

At the screen you can see, that I fixed path of libraries, because I thinked, that it wiil help. Also I imported modules at the next format `.options.test_options import TestOptions` and this doesn't work ☹️

All libs were installed to the venv of this project.

**Comment by guoqc3** [comment]
Has the problem been solved? Could you tell me how to solve the same problem I have

**Comment by zhangmozhe** [comment]
We've fixed the issue. Please have a try.

**Comment by nishuer** [comment]
try use `--GPU -1`
