### ISSUE TITLE
[New Feature] Colourize Image

### ISSUE THREAD

**Issue by Aayush-hub** [microsoft/Bringing-Old-Photos-Back-to-Life#176]
Add a functionality by which users can convert their black and white images to coloured images. It looks very cool and interesting feature. We can make a GUI in which people can upload their black and white image and then convert it to coloured by clicking a button and then save the result image in their PC.

**Comment by Aayush-hub** [comment]
> Add a functionality by which users can convert their black and white images to coloured images. It looks a cool and interesting feature. We can make a GUI in which people can upload their black and white image and then convert it to coloured by clicking a button and then save the result image in their PC.

@zhangmozhe What do you think about this feature, can I work on it??

**Comment by Aayush-hub** [comment]
@zhangmozhe @raywzy Can I get any comments/updates on this feature. Should this be implemented? Or should I close this issue??

**Comment by zhangmozhe** [comment]
Hi @Aayush-hub, thanks for your suggestion. I think the image colorization is out of the scope of this project. People may just like to restore the quality rather than colonization. Since the high-quality colorization itself is very complex, we would like to create a new project rather than embedding this feature in this repo.

**Comment by Aayush-hub** [comment]
> Hi @Aayush-hub, thanks for your suggestion. I think the image colorization is out of the scope of this project. People may just like to restore the quality rather than colonization. Since the high-quality colorization itself is very complex, we would like to create a new project rather than embedding this feature in this repo.

@zhangmozhe Oky great idea, looking forward to contribute to that project. Let me know when it will be started!

**Comment by Aayush-hub** [comment]
> > Hi @Aayush-hub, thanks for your suggestion. I think the image colorization is out of the scope of this project. People may just like to restore the quality rather than colonization. Since the high-quality colorization itself is very complex, we would like to create a new project rather than embedding this feature in this repo.
> 
> @zhangmozhe Oky great idea, looking forward to contribute to that project. Let me know when it will be started!

@zhangmozhe Can I know are we working on this?

**Comment by zhangmozhe** [comment]
Hello @Aayush-hub, sorry for the late reply. We will work on this on a standalone project.

**Comment by Aayush-hub** [comment]
> Hello @Aayush-hub, sorry for the late reply. We will work on this on a standalone project.

@zhangmozhe Sure, waiting for it.
