### ISSUE TITLE
An issue about test step

### ISSUE THREAD

**Issue by Mr-doraemon** [microsoft/Bringing-Old-Photos-Back-to-Life#177]
In the training mapping network, I visualized the results quite well. Why did the results fail when I tested them? I was sure that 
no overfitting had occurred, because I tested the training data with the same results. At the same time, I also confirm that my 
inference part is consistent with the forward part.
    Can you give me help, please?

**Comment by raywzy** [comment]
Hi, have you visualized the reconstruction resutls of VAE?

**Comment by Mr-doraemon** [comment]
> 
> 
> Hi, have you visualized the reconstruction resutls of VAE?

I have solved the above problems. Actually, I visualized the result of Vae reconstruction, but the result of Vae reconstruction in the training stage was slightly better than that in the test stage.
