### ISSUE TITLE
what is "old_face_label_folder".

### ISSUE THREAD

**Issue by geshihuazhong** [microsoft/Bringing-Old-Photos-Back-to-Life#178]
I found it seem need a label? but how to generate the label is not mentioned in Readme and Jouranl paper.

line26 of Face_Enhancement/data/face_dataset.py

        image_path = os.path.join(opt.dataroot, opt.old_face_folder)
        label_path = os.path.join(opt.dataroot, opt.old_face_label_folder)

**Comment by raywzy** [comment]
Hi, it means the face parsing map. We try to leverage such prior information to improve the restoration results, but hardly find the effectiveness. You could just ignore the path.
