### ISSUE TITLE
add GFPGAN for face restoring

### ISSUE THREAD

**Issue by GOZARCK** [microsoft/Bringing-Old-Photos-Back-to-Life#179]
it would be nice to add https://github.com/TencentARC/GFPGAN
for face restoration
![Solvay_conference_1927_19](https://user-images.githubusercontent.com/14808854/123645821-0c6b7a00-d7fd-11eb-8e0e-6209a05e40fc.png)

**Comment by syfbme** [comment]
This model will do colorization which is not compatible to current model.
