### ISSUE TITLE
something is wrong 

### ISSUE THREAD

**Issue by Lexapro17** [microsoft/Bringing-Old-Photos-Back-to-Life#180]
I've been trying to run this awesome script for days, but when I run it

> python run.py --input_folder ./dopoprawy \
>               --output_folder ./poprawione \
>               --GPU 0 \
>               --with_scratch

it returns:

> Running Stage 1: Overall restoration
> initializing the dataloader
> python: symbol lookup error: /home/lexapro/.pyenv/versions/3.6.0/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
> You are using NL + Res
> Finish Stage 1 ...
> 
> 
> Running Stage 2: Face Detection
> Finish Stage 2 ...
> 
> 
> Running Stage 3: Face Enhancement
> The main GPU is 
> 0
> dataset [FaceTestDataset] of size 0 was created
> The size of the latent vector size is [8,8]
> Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
> hi :)
> Finish Stage 3 ...
> 
> 
> Running Stage 4: Blending
> Finish Stage 4 ...
> 
> 
> All the processing is done. Please check the results.

My configuration is: 
Python 3.6.0 installed by pyenv,
Ubuntu 18.04, 
I did everything like in tutorial with requirements.txt

also:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.42.01    Driver Version: 470.42.01    CUDA Version: 11.4     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  On   | 00000000:26:00.0  On |                  N/A |
> |  0%   50C    P0    32W / 180W |    205MiB /  6075MiB |      1%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A       996      G   /usr/lib/xorg/Xorg                114MiB |
> |    0   N/A  N/A      1137      G   /usr/bin/gnome-shell               88MiB |
> +-----------------------------------------------------------------------------+
> 

Please, help :)))

**Comment by raywzy** [comment]
Hi, could you upgrade the python to 3.6.1 or greater and then have a try?

**Comment by Lexapro17** [comment]
Hi, Yes I've tried many version, the last 3.7.10 because I saw it on demo compilator.
Maybee I should remove cash memory from pip and use other version but which ?
On other versions I got other bugs.

**Comment by raywzy** [comment]
Maybe you could try to re-create a new environment through conda, then install other requriments. 
`conda create -n env_name python=3.6.5`
