### ISSUE TITLE
Alternative of Cuda

### ISSUE THREAD

**Issue by KevinJue** [microsoft/Bringing-Old-Photos-Back-to-Life#188]
Hello,

i'm actually running your tool on Mac, problem is, Mac have Intel/Radeon GPU so by using Cuda we cannot run the script with option 
--GPU 0

is it possible to imagine an alternative by using OpenCL ?

**Comment by p1x31** [comment]
I reckon your best bet is to use CPU, alternatively, you might be able to retrain with the [Vulkan-NCNN](https://github.com/Tencent/ncnn) but it is just going to be very tedious.

**Comment by ikzh1** [comment]
Hi
