### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found. 

### ISSUE THREAD

**Issue by cloudweather** [microsoft/Bringing-Old-Photos-Back-to-Life#2]
Hi, thank you for this amazing work.

Unfortunately, I have run into 2 issues while trying to run this on Windows 10 Anaconda Prompt

my input
```
python run.py --input_folder input --output_folder output --GPU 0 --with_scratch
```

the error
```
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
directory of testing image: input
Traceback (most recent call last):
  File "detection.py", line 151, in <module>
    main(config)
  File "detection.py", line 85, in main
    imagelist = os.listdir(config.test_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'input'
You are using NL + Res
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    input_loader = os.listdir(opt.test_input)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'output\\stage_1_restore_output\\masks\\input'
Finish Stage 1 ...


Running Stage 2: Face Detection
Traceback (most recent call last):
  File "detect_all_dlib.py", line 24, in <module>
    import dlib
  File "E:\Anaconda3\envs\restore\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed: The specified module could not be found.
Finish Stage 2 ...


Running Stage 3: Face Enhancement
The main GPU is
0
Traceback (most recent call last):
  File "test_face.py", line 15, in <module>
    dataloader = data.create_dataloader(opt)
  File "G:\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\data\__init__.py", line 13, in create_dataloader
    instance.initialize(opt)
  File "G:\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\data\face_dataset.py", line 29, in initialize
    image_list = os.listdir(image_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: './datasets/cityscapes/output\\stage_2_detection_output'
Finish Stage 3 ...


Running Stage 4: Blending
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 23, in <module>
    import dlib
  File "E:\Anaconda3\envs\restore\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed: The specified module could not be found.
Finish Stage 4 ...


All the processing is done. Please check the results.
```
The output folder is empty

I already have CUDA 10.2 and cudnn64_7.dll in PATH, but the dlib error still pops up.
And I have no idea how to solve the backslashes issue.

How can I solve this?
Thank you!

**Comment by zhangmozhe** [comment]
It seems that the code cannot locate the input folder. Have you tried to use absolute path?

**Comment by raywzy** [comment]
After checking the error information, I suggest you could use the absolute path. Besides, it seems that the dlib library is not installed correctly which is used for face detection. I have not met this problem before.

**Comment by cloudweather** [comment]
Having the absolute path (the full file path) works. But still can't solve the dlib problem. Any tips?
Also is there a way to bypass the CUDA out of memory? Should I like use the CPU or make the input image smaller?

```
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
directory of testing image: G:\Bringing-Old-Photos-Back-to-Life\input
processing 31e3reott1i51.jpg
Traceback (most recent call last):
  File "detection.py", line 151, in <module>
    main(config)
  File "detection.py", line 123, in main
    P = torch.sigmoid(model(scratch_image))
  File "E:\Anaconda3\envs\restore\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\Bringing-Old-Photos-Back-to-Life\Global\detection_models\networks.py", line 119, in forward
    x = up(x, blocks[-i - 1])
  File "E:\Anaconda3\envs\restore\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\Bringing-Old-Photos-Back-to-Life\Global\detection_models\networks.py", line 167, in forward
    out = torch.cat([up, crop1], 1)
RuntimeError: CUDA out of memory. Tried to allocate 368.00 MiB (GPU 0; 8.00 GiB total capacity; 5.66 GiB already allocated; 71.71 MiB free; 5.77 GiB reserved in total by PyTorch)
You are using NL + Res
Finish Stage 1 ...


Running Stage 2: Face Detection
Traceback (most recent call last):
  File "detect_all_dlib.py", line 24, in <module>
    import dlib
  File "E:\Anaconda3\envs\restore\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed: The specified module could not be found.
Finish Stage 2 ...


Running Stage 3: Face Enhancement
The main GPU is
0
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...


Running Stage 4: Blending
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 23, in <module>
    import dlib
  File "E:\Anaconda3\envs\restore\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed: The specified module could not be found.
Finish Stage 4 ...


All the processing is done. Please check the results.
```

Some screenshots that might help:
![qwrfqwsss](https://user-images.githubusercontent.com/29135514/93606127-397f3680-f9fa-11ea-9ca5-681376f05bb3.PNG)
![qweqwes](https://user-images.githubusercontent.com/29135514/93606132-3ab06380-f9fa-11ea-8ae4-dec8bf41f1ca.PNG)
![wqeqwewdeew](https://user-images.githubusercontent.com/29135514/93606134-3ab06380-f9fa-11ea-8d92-388425a34d35.PNG)

**Comment by zhangmozhe** [comment]
> Having the absolute path (the full file path) works. But still can't solve the dlib problem. Any tips?
> Also is there a way to bypass the CUDA out of memory? Should I like use the CPU or make the input image smaller?
> 
> ```
> Running Stage 1: Overall restoration
> initializing the dataloader
> model weights loaded
> directory of testing image: G:\Bringing-Old-Photos-Back-to-Life\input
> processing 31e3reott1i51.jpg
> Traceback (most recent call last):
>   File "detection.py", line 151, in <module>
>     main(config)
>   File "detection.py", line 123, in main
>     P = torch.sigmoid(model(scratch_image))
>   File "E:\Anaconda3\envs\restore\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "G:\Bringing-Old-Photos-Back-to-Life\Global\detection_models\networks.py", line 119, in forward
>     x = up(x, blocks[-i - 1])
>   File "E:\Anaconda3\envs\restore\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "G:\Bringing-Old-Photos-Back-to-Life\Global\detection_models\networks.py", line 167, in forward
>     out = torch.cat([up, crop1], 1)
> RuntimeError: CUDA out of memory. Tried to allocate 368.00 MiB (GPU 0; 8.00 GiB total capacity; 5.66 GiB already allocated; 71.71 MiB free; 5.77 GiB reserved in total by PyTorch)
> You are using NL + Res
> Finish Stage 1 ...
> 
> 
> Running Stage 2: Face Detection
> Traceback (most recent call last):
>   File "detect_all_dlib.py", line 24, in <module>
>     import dlib
>   File "E:\Anaconda3\envs\restore\lib\site-packages\dlib\__init__.py", line 19, in <module>
>     from _dlib_pybind11 import *
> ImportError: DLL load failed: The specified module could not be found.
> Finish Stage 2 ...
> 
> 
> Running Stage 3: Face Enhancement
> The main GPU is
> 0
> dataset [FaceTestDataset] of size 0 was created
> The size of the latent vector size is [8,8]
> Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
> hi :)
> Finish Stage 3 ...
> 
> 
> Running Stage 4: Blending
> Traceback (most recent call last):
>   File "align_warp_back_multiple_dlib.py", line 23, in <module>
>     import dlib
>   File "E:\Anaconda3\envs\restore\lib\site-packages\dlib\__init__.py", line 19, in <module>
>     from _dlib_pybind11 import *
> ImportError: DLL load failed: The specified module could not be found.
> Finish Stage 4 ...
> 
> 
> All the processing is done. Please check the results.
> ```
> 
> Some screenshots that might help:
> ![qwrfqwsss](https://user-images.githubusercontent.com/29135514/93606127-397f3680-f9fa-11ea-9ca5-681376f05bb3.PNG)
> ![qweqwes](https://user-images.githubusercontent.com/29135514/93606132-3ab06380-f9fa-11ea-8ae4-dec8bf41f1ca.PNG)
> ![wqeqwewdeew](https://user-images.githubusercontent.com/29135514/93606134-3ab06380-f9fa-11ea-8d92-388425a34d35.PNG)

Sorry that this work requires the CUDA to work. If code runs out of memory, you can resize the image a little bit. For the dlib installation issue, maybe you can try to use WSL2 on windows. 

For convenient usage, you can also try our Colab demo which allows uploading your own photos.
