### ISSUE TITLE
Make code python3 friendly

### ISSUE THREAD

**Issue by westscz** [microsoft/Bringing-Old-Photos-Back-to-Life#20]
RIght now, because of hardcoded paths with usage of `python` command there is no possibility to make full run with `python3`

**Comment by zhangmozhe** [comment]
Sorry for the inconvenience. One workaround is to add `alias python=python3` into your `~/.bashrc` file.

**Comment by xRealNeon** [comment]
You can also install `python-is-python3`

**Comment by imsubhamsingh** [comment]
you can use python-modernize to utilize it to make Python 2 code more modern with the intention of eventually porting it over to Python 3.
