### ISSUE TITLE
The result not good as introduce

### ISSUE THREAD

**Issue by hungtooc** [microsoft/Bringing-Old-Photos-Back-to-Life#207]
Hi, thank for the source code.
I found the result not good as your introduce.
introduce in README we have:
https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/blob/master/imgs/HR_result.png
but when i tested it on colab with this image (which croped from big image):
![cuted](https://user-images.githubusercontent.com/24487114/145739403-4ce48d31-da6e-4535-8640-fbcb7991a5e3.png)
The result wasn't good:
![download](https://user-images.githubusercontent.com/24487114/145739634-4a960189-8587-46d3-bd3d-c9d989257885.png)

Why?, thanks.

**Comment by davaram** [comment]
Same question, hope to reply

**Comment by MGSousa** [comment]
Same as mine ...

**Comment by tuapuikia** [comment]
I don't have a problem. The result is the same as advertised.
CUDA with RTX 2080 8GB vram.

![image](https://user-images.githubusercontent.com/7571272/199910188-9908522e-67cb-4056-87ec-963b911b9fb3.png)
