### ISSUE TITLE
太拉垮了。。 动不动就超出大小。500多K的东西都处理不了。

### ISSUE THREAD

**Issue by xclidongbo** [microsoft/Bringing-Old-Photos-Back-to-Life#212]
太拉垮了。。 动不动就超出大小。500多K的东西都处理不了。

**Comment by davaram** [comment]
Add -HR parameter can be solved

Each server has its own processing limit, my maximum processing resolution is 2300*2300

**Comment by tongchangD** [comment]
> Add -HR parameter can be solved
> 
> Each server has its own processing limit, my maximum processing resolution is 2300*2300

What is your server
