### ISSUE TITLE
Inference on CPP code

### ISSUE THREAD

**Issue by FrancescaCi** [microsoft/Bringing-Old-Photos-Back-to-Life#229]
Hi,
I am very interesting on your project, I would like to know if it is possible to inference the pretrained model directly on a test set of images but using CPP implementation. If yes, can I ask some help for some scratch about it?
Thank you for your feedback.
Best

**Comment by tongchangD** [comment]
I was building this and encountered the following problem when PTH was transferred to ONNX.

in Face_Enhancement.

```
RuntimeError: Unsupported: ONNX export of batch_norm for unknown channel size.
```

**Comment by FrancescaCi** [comment]
Thank you so much for your suggestion!
A question, if you try the model for global-restoration only to apply directly on images, is the result the same?

**Comment by tongchangD** [comment]
haven't tried
