### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by florianlv1** [microsoft/Bringing-Old-Photos-Back-to-Life#234]
Hi, I am getting a lot of errors but I do not know how to handle them. I tried googling but I could not find a proper solution. 

What I am trying to do right now is to use the GUI to modify one of the testphotos. I can open the GUI but when running it does not work.

This is the first error I am getting. Maybe resolving this resolves the other following errors.
```
UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
```
it points to this codeline:

`example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])`

Thanks for any help

**Comment by gaseosaluz** [comment]
This could be because the version of NumPy that you are picking up. If you are using virtual Environments try creating another to test this and install an older version of NumPy. Hopefully this helps.

**Comment by florianlv1** [comment]
thank you
