### ISSUE TITLE
Don't know how to train VAE_B_scratch,can't find 

### ISSUE THREAD

**Issue by CodeMadUser** [microsoft/Bringing-Old-Photos-Back-to-Life#238]
Don't know how to train VAE_B_scratch

**Comment by Ssakura-go** [comment]
> Don't know how to train VAE_B_scratch
Hi, dear friend~
Did you solve this problem now?

**Comment by CodeMadUser** [comment]
> > Don't know how to train VAE_B_scratch
> > Hi, dear friend~
> > Did you solve this problem now?

hello,training VAE_B_scratch is the same to train VAE_A_quality.you can try it on.

**Comment by Ssakura-go** [comment]
> > > Don't know how to train VAE_B_scratch
> > > Hi, dear friend~
> > > Did you solve this problem now?
> 
> hello,training VAE_B_scratch is the same to train VAE_A_quality.you can try it on.

Thanks for your quick reply. I should prepare the datasets with scratches. Right?
