### ISSUE TITLE
builder windows

### ISSUE THREAD

**Issue by YongChingShieh** [microsoft/Bringing-Old-Photos-Back-to-Life#239]
some one builder windows version ? Multiple installations of dlib failed fxxk python
有人能发布一下windows版本吗 Linux安装dlib N多次都失败 这python也太恶心了

**Comment by shawtux** [comment]
@YongChingShieh I had alot of trouble as well.

I made sure that I had the following installed:
![image](https://user-images.githubusercontent.com/6968896/180267702-dae52f00-6aa3-4b6f-84a4-70aa0654ae8e.png)

![image](https://user-images.githubusercontent.com/6968896/180267808-17dbc613-b01c-4966-9b40-878a67d373aa.png)

Also made sure I had rebooted and had the paths in the environment variable

![image](https://user-images.githubusercontent.com/6968896/180268248-b35c3700-84af-41c2-8179-628e6354b0c9.png)
(red lines is c:\user\<username>

Also used the following guide as well:"
https://medium.com/analytics-vidhya/how-to-install-dlib-library-for-python-in-windows-10-57348ba1117f

Then

**Comment by YongChingShieh** [comment]
> @YongChingShieh I had alot of trouble as well.
> 
> I made sure that I had the following installed: ![image](https://user-images.githubusercontent.com/6968896/180267702-dae52f00-6aa3-4b6f-84a4-70aa0654ae8e.png)
> 
> ![image](https://user-images.githubusercontent.com/6968896/180267808-17dbc613-b01c-4966-9b40-878a67d373aa.png)
> 
> Also made sure I had rebooted and had the paths in the environment variable
> 
> ![image](https://user-images.githubusercontent.com/6968896/180268248-b35c3700-84af-41c2-8179-628e6354b0c9.png) (red lines is c:\user<username>
> 
> Also used the following guide as well:" https://medium.com/analytics-vidhya/how-to-install-dlib-library-for-python-in-windows-10-57348ba1117f
> 
> Then

I used windows and  Linux ,unsuccessful
