### ISSUE TITLE
Can we use larger file size (pixels) when running in python locally compare to running in Colab locally ?

### ISSUE THREAD

**Issue by hlalibe** [microsoft/Bringing-Old-Photos-Back-to-Life#26]
I can run successfully your Colab notebook locally, runs nicely.
The only issue is the file size in pixels is rather limited.
Is there a way to run it with large files in local Colab ?
Or should I run it under Python 3.6 ? Is there a file size limit under Python ?

**Comment by zhangmozhe** [comment]
May you can refer to https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/3#issuecomment-699988743
