### ISSUE TITLE
Training Data and Training Code

### ISSUE THREAD

**Issue by wushunshun** [microsoft/Bringing-Old-Photos-Back-to-Life#27]
Hi, could you release the training data and training code? Thank you very much!

**Comment by zhangmozhe** [comment]
We will release the training code soon, but possibly after the CVPR deadline... Since the dataset has copyright issue, we do not intend to release it. Thanks for your understanding.

**Comment by wushunshun** [comment]
> We will release the training code soon, but possibly after the CVPR deadline... Since the dataset has copyright issue, we do not intend to release it. Thanks for your understanding.

Thank you for your reply. May I ask if the training code release time is the end of November or the end of December or next year? Thank you again !

**Comment by howardgriffin** [comment]
Also waiting for the training code...

**Comment by ywj95** [comment]
waiting for the training code

**Comment by SikandAlex** [comment]
CVPR was one month ago so is there any chance this training code could be released? I am in academia and I find it frustrating how much AI research is not reproducible or the corresponding code is not released or maintained. Regardless, huge congratulations to the team for the submission of this paper. But please can we see the training code?

**Comment by jmandivarapu1** [comment]
waiting for the training code. Is there any update on this?

**Comment by wahyuway** [comment]
Still no ETA on Training Code? @zhangmozhe

**Comment by siam7tong** [comment]
thanks  ,waiting for the training code too

**Comment by HymEric** [comment]
waiting, too.

**Comment by dunky11** [comment]
watiting too

**Comment by XGBoost** [comment]
waiting too

**Comment by XGBoost** [comment]
waiting

**Comment by SikandAlex** [comment]
Yet again... the academics responsible for this work and paper refuse to release the training code even though it obviously exists and would be easy to distribute. What use is only inference code? The scratch removal works relatively well but DeOldify has far better super-resolution and facial enhancement than this paper in my experiments. It's typical of Microsoft, Amazon, and Google for this type of behavior. Don't pretend to open-source your code if you aren't actually going to. The amount of claimed state-of-the-art repos that are incomplete or sloppy messes is astounding.

**Comment by zhangmozhe** [comment]
Sorry for the late reply. We've just released the training code and welcome to have a try. Please open a new issue if there is an error when trying the training code.
