### ISSUE TITLE
CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by west5211** [microsoft/Bringing-Old-Photos-Back-to-Life#28]
when I run code，get the error like thie
"RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable"

I already installed cuna,nvidia driver,check the processes, this is the info
(venv) dash@dash-KVM:~/Bringing-Old-Photos-Back-to-Life-master$ nvidia-smi 
Fri Oct 23 11:07:33 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID T4-8Q          On   | 00000000:00:09.0 Off |                  N/A |
| N/A   N/A    P8    N/A /  N/A |    592MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

GPU info:
 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GRID T4-8Q"
  CUDA Driver Version / Runtime Version          10.2 / 10.2
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 8192 MBytes (8589934592 bytes)
  (40) Multiprocessors, ( 64) CUDA Cores/MP:     2560 CUDA Cores
  GPU Max Clock rate:                            1590 MHz (1.59 GHz)
  Memory Clock rate:                             5001 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 4194304 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 9
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.2, NumDevs = 1
Result = PASS

**Comment by zhangmozhe** [comment]
Maybe you do the simplest test:

```
import torch
print(torch.cuda.is_available())
```

If cuda cannot be detected by torch,  maybe you can try

```
import torch
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
print(torch.cuda.is_available())
```

**Comment by west5211** [comment]
> 也许您可以在python中做最简单的测试：
> 
> ```
> import torch
> print(torch.cuda.is_available())
> ```
> 
> 如果割炬无法检测到CUDA，也许您可​​以尝试
> 
> ```
> import torch
> import os
> os.environ["CUDA_VISIBLE_DEVICES"] = '0'
> print(torch.cuda.is_available())
> ```

thank for the replay，my cuda looks normal

(venv) dash@dash-KVM:~/Bringing-Old-Photos-Back-to-Life-master$ python
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> import os
>>> os.environ["CUDA_VISIBLE_DEVICES"] = '0'
>>> print(torch.cuda.is_available())
True
>>>

**Comment by zhangmozhe** [comment]
Maybe you can try to run with --GPU -1. Or you can raise the issue in the official PyTorch repo as it seems the problem of PyTorch installation.
