### ISSUE TITLE
ImportError: No module named torch.autograd

### ISSUE THREAD

**Issue by akenateb** [microsoft/Bringing-Old-Photos-Back-to-Life#31]
Hello all!, It seems install is ok

`Requirement already satisfied: torchvision in /usr/local/lib/python3.8/dist-packages (0.8.1)
Requirement already satisfied: torch==1.7.0 in /usr/local/lib/python3.8/dist-packages (from torchvision) (1.7.0)
Requirement already satisfied: pillow>=4.1.1 in /usr/lib/python3/dist-packages (from torchvision) (7.2.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from torchvision) (1.19.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from torch==1.7.0->torchvision) (0.18.2)
Requirement already satisfied: typing-extensions in /usr/lib/python3/dist-packages (from torch==1.7.0->torchvision) (3.7.4.3)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.8/dist-packages (from torch==1.7.0->torchvision) (0.6)
`
Guided by Installation instructions all ok except when I launch:
`# python run.py --input_folder /imgs/ --output_folder /imgs/output/ --GPU 0`

`Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch.autograd import Variable
ImportError: No module named torch.autograd
Traceback (most recent call last):
  File "run.py", line 91, in <module>
    for x in os.listdir(stage_1_results):
OSError: [Errno 2] No such file or directory: '/imgs/output/stage_1_restore_output/restored_image'`

`root@DESKTOP-H0VF09L:/home/akenateb/Bringing-Old-Photos-Back-to-Life# python
Python 2.7.18 (default, Apr 20 2020, 20:30:41) 
[GCC 9.3.0] on linux2`
`
What I am doing wrong?
Thanks in advance.

**Comment by samiraguiar** [comment]
Does `python` in your system point to Python 2? If so that might be the case. See [#20](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/20)

**Comment by akenateb** [comment]
I have modified ~/.bashrc adding alias. Same error.

**Comment by xujimu** [comment]
> 感谢您的回答。
> 我修改了〜/ .bashrc添加别名。同样的错误。
> 
> 有人知道我在做什么错吗？
> 
> 最好的祝福。

Have you solved it, I have this problem too

**Comment by vlada1001** [comment]
@akenateb Do you have NVIDIA GPU with CUDA enabled?

**Comment by akenateb** [comment]
[SOLVED] https://docs.nvidia.com/cuda/wsl-user-guide/index.html
If you follow this guide (**all steps**) and finally you can do `./BlackScholes` you have fixed it.

Best Regards.

**Comment by phadytou** [comment]
Hello word

**Comment by NaturallyAsh** [comment]
I am experiencing this problem on my Mac Catalina. Any suggestions? pip3 shows torch and torchvision packages but I am still getting a torch.autograd error.

**Comment by nobreak** [comment]
> I am experiencing this problem on my Mac Catalina. Any suggestions? pip3 shows torch and torchvision packages but I am still getting a torch.autograd error.

For me the same on MacOS Catalina, any news ?

**Comment by zhonglaoban** [comment]
> > I am experiencing this problem on my Mac Catalina. Any suggestions? pip3 shows torch and torchvision packages but I am still getting a torch.autograd error.
> 
> For me the same on MacOS Catalina, any news ?
> 
> I updated to python 3.8.7 and added to ~/.bash_profile the alias 'alias python=python3' I also installed the related frameworks
> 
> Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.7.1) Requirement already satisfied: torchvision in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.8.2)
> 
> UPDATE: I found a solution now for my case. I found out that the on terminal called run.py script was working with python3 but all other py scripts which was called by code was running with python2. I don't know why (i changed the alias in ~/.bash_profile and restartet the terminal session, but still this issue. So my solution was to just change in Global/test.py all "python ..." calls to python3.
> 
> Not it runs, but on mac i have to switch off the use of GPU by "--gpu_ids -1" - there is no support for it (error: "AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'")

when the error(error: "AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'") occured. just set GPU to '-1' like this `--GPU -1`

**Comment by ChitturiSaiSuman** [comment]
Changing `python` in [line #55 in the run.py](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/blob/33875eccf4ebcd3665cf38cc56f3a0ce563d3a9c/run.py#L55) to `python3` worked for me. But, sadly I don't have an NVIDIA GPU in my Laptop.
