### ISSUE TITLE
Software installation/use tutorial

### ISSUE THREAD

**Issue by m2asp** [microsoft/Bringing-Old-Photos-Back-to-Life#36]
Could someone insert an installation and use tutorial for Windows 10?
I have installed Python, Anaconda, PyThorc and Nvidia Cuda, but I didn't understand how to install and use this artificial intelligence software for restoring old photos (sorry if my English is bad but I'm Italian and I'm using Google Translate)

**Comment by ModnarUser** [comment]
As mentioned in  [another thread](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/24#issuecomment-707612796) it is definetly possible to Install and run the software on Windows 10. 

Could you elaborate on what exactly your struggeling with? Did you follow the readme and could you execute the setup commands?

**Comment by m2asp** [comment]
I downloaded and opened the attached zip file, but after this I don't know how to continue

**Comment by ModnarUser** [comment]
Ok. Since you want to run the code on Windows, but the setup commands are written for a unix-like shell, you will need to install a shell emulator that runs on Windows. I would recommend installing the [git-bash](https://gitforwindows.org/). Launch an instace of the git bash and navigate to a directory where you want to place the files of this project, e.g.
```
cd /c/users/your_user_name/documents/
```
Next, clone the repository with
```
git clone https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life
```
Now you can continue by entering the commands mentioned in the readme section __Installation__ to setup the project.

**Comment by m2asp** [comment]
I installed and opened git-hash and was able to execute the instructions you gave me, but now I don't know how to continue.
I tried to write in the open instance of git-hash the code written in the first installation section of the readme file, but I must have done something wrong because the instance tells me "too many arguments", what do I do?

**Comment by ModnarUser** [comment]
I guess you are referring to the first block of commands:
```
cd Face_Enhancement/models/networks/
git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch
cp -rf Synchronized-BatchNorm-PyTorch/sync_batchnorm .
cd ../../../
```
Pleased specify __where exactly__ it fails and provide the __whole error messages__ you receive. 
Have you tried entering the commands line by line?
Refer to the manpages of the [`cd`](https://man7.org/linux/man-pages/man1/cd.1p.html),  [`cp`](https://man7.org/linux/man-pages/man1/cp.1.html) and  [`git`](https://man7.org/linux/man-pages/man1/git.1.html) commands if you are still struggeling with entering the installation commands.

**Comment by ModnarUser** [comment]
Also make sure you are inside the top level directory when entering the commands. E.g. navigate into it via `cd Bringing-Old-Photos-Back-to-Life`.

**Comment by m2asp** [comment]
https://imgur.com/YSLJwFb

**Comment by ModnarUser** [comment]
?

**Comment by m2asp** [comment]
I took a screenshot of that git-bash instance with the related error.
Can you see it?

**Comment by ModnarUser** [comment]
Ah I see. You have to either enter the commands line by line or seperate them with a `;`

**Comment by m2asp** [comment]
Ok, I was able to perform this step, now what should I do?

**Comment by zhangmozhe** [comment]
The easy way is to use our Colab demo in which you can upload your photos for processing.

**Comment by m2asp** [comment]
> The easy way is to use our Colab demo in which you can upload your photos for processing.

Ok, but what should I do to run this demo on google colab? I did not get it

**Comment by zhangmozhe** [comment]
https://colab.research.google.com/drive/1NEm6AsybIiC5TwTU_4DqDkQO0nFRB-uA?usp=sharing. Change the runtype to GPU. Then click the cells and run the cells with Ctrl+Enter. You can notice the running output and the prompt to upload your own photos.

**Comment by m2asp** [comment]
After I run the cell, it gives me this error:
NameError                                 Traceback (most recent call last)
<ipython-input-5-5d8b874dcecb> in <module>()
      2 import shutil
      3 
----> 4 upload_path = os.path.join(basepath, "test_images", "upload")
      5 upload_output_path = os.path.join(basepath, "upload_output")
      6 

NameError: name 'os' is not defined

**Comment by zhangmozhe** [comment]
Did you run the runs from the very beginning?

**Comment by m2asp** [comment]
I ran this cell:
https://imgur.com/a/e3Owj3Z

**Comment by zhangmozhe** [comment]
Hi, you need to run the notebook from the very beginning. Those cells set up the environment to run our algorithm.

**Comment by phadytou** [comment]
You want go to bad
Wis me

**Comment by m2asp** [comment]
I ran all the cells together this time, however the software gives me this error when it gets to the "Restore the photos with scratches" section:
a.png
-------------------------------------------------- -------------------------
FileNotFoundError Traceback (most recent call last)
<ipython-input-8-3121ae23a960> in <module> ()
      10 print (filename)
      11 image_original = PIL.Image.open (os.path.join (input_path, filename))
---> 12 image_restore = PIL.Image.open (os.path.join (output_path, 'final_output', filename))
      13
      14 display (make_grid (image_original, image_restore))

/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open (fp, mode)
    2807
    2808 if filename:
-> 2809 fp = builtins.open (filename, "rb")
    2810 exclusive_fp = True
    2811

FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/output/final_output/a.png'

**Comment by phadytou** [comment]
Thank you so much
