### ISSUE TITLE
Where we can see the results of it ?

### ISSUE THREAD

**Issue by T4securitys** [microsoft/Bringing-Old-Photos-Back-to-Life#38]
Sorry for asking I am a newibe programer pls make a website in which we can see the results

**Comment by gitatmax** [comment]
[This has a great number of examples](http://raywzy.com/Old_Photo/)

**Comment by chelli22** [comment]
> @T4securitys [This has a great number of examples](http://raywzy.com/Old_Photo/)

**Comment by ChrisChiera** [comment]
> @T4securitys [This has a great number of examples](http://raywzy.com/Old_Photo/)

That link is broken.

**Comment by ChrisChiera** [comment]
> @T4securitys [This has a great number of examples](http://raywzy.com/Old_Photo/)

That link is broken.
