### ISSUE TITLE
googlelab restoration failed

### ISSUE THREAD

**Issue by iam57-2020** [microsoft/Bringing-Old-Photos-Back-to-Life#43]
like this,log was not propose any wrong,but i can't change it
<img width="1286" alt="截屏2020-11-17 下午12 57 23" src="https://user-images.githubusercontent.com/54011711/99348627-fdbafd00-28d4-11eb-9fd5-dfc9e2630121.png">

**Comment by alylynn1426** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by phadytou** [comment]
hello word

**Comment by zhangmozhe** [comment]
We do not encounter the problem like this. Can you please try again and report the issue?
