### ISSUE TITLE
Download mirrors

### ISSUE THREAD

**Issue by LeRoyJulian** [microsoft/Bringing-Old-Photos-Back-to-Life#49]
Here are better links to download checkpoints, because you don't have hours to waste downloading it on that poor Azure Blob Storage.
Face_Enhancement: https://we.tl/t-5tZD5lB3O6
Global: https://we.tl/t-zsrsNnOkGN

**Comment by zhangmozhe** [comment]
The mirror is expired now, so I will close this issue.
