### ISSUE TITLE
how to run code with CPU?

### ISSUE THREAD

**Issue by milancelanmi** [microsoft/Bringing-Old-Photos-Back-to-Life#55]
First of all, thank you for project. I was able to install on windows, but because my gpu doesnt have vram for large resolution images, (2-8MPx scanned archive photos), and cuda out of memory always, decided to try with pytorch for cpu. I have Ryzen 1700 CPU, and know that cpu mode is much slower, but have patience and will wait untill final output render. Saw that models updated to support cpu but dont know how to run code properly....Tried with modifications to run on cpu but without success.... please help :)
Thank you

**Comment by minhchuvolam** [comment]
I would like to know how to run this on CPU as well.

**Comment by lt94** [comment]
Simplely set argument **--GPU -1**

```python
# base_options.py
self.parser.add_argument(
            "--gpu_ids", type=str, default="0", help="gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU"
)
```

**Comment by milancelanmi** [comment]
thank you. but not working on --with_scratch mode

**Comment by lt94** [comment]
yeah, i got same problem when working on --with_scratch mode,it doesn't seem to support CPU mode on scratched image

**Comment by lt94** [comment]
i made a PR for this one https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/pull/60

**Comment by milancelanmi** [comment]
I have reinstalled python and conda to try again..redownloaded all dependiencies and updated project from this page
CPU mode works excellent with argument --GPU -1 for overall restoration
but when I try to load scratch remove model on CPU with --GPU -1 argument, new error message:
`python run.py --input_folder /photo_restoration/test_images/old_w_scratch --output_folder /photo_restoration/output/ --GPU -1 --with_scratch
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
Traceback (most recent call last):
  File "detection.py", line 155, in <module>
    main(config)
  File "detection.py", line 80, in main
    model.to(config.GPU)
  File "C:\Users\Milan\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 600, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Device index must not be negative
You are using NL + Res
Finish Stage 1 ...


Running Stage 2: Face Detection
Finish Stage 2 ...


Running Stage 3: Face Enhancement
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...


Running Stage 4: Blending
Finish Stage 4 ...


All the processing is done. Please check the results.`
No output photo generated.

**Comment by lt94** [comment]
@milancelanmi  you are right,i forgot to update dection.py~~

**Comment by milancelanmi** [comment]
And one more question please. On higher photo resolutions (>1Mpx) --with_scratch mode checked , code returns cpu ram related allocation errors in random number of bytes. And appears message  to buy more RAM. My PC have 16GB DDR4 RAM . I am serious to buy another 16GB kit, if that will solve the problem.

**Comment by Faisalrahi1234** [comment]
initializing the dataloader
model weights loaded
directory of testing image: /mnt/batch/tasks/shared/LS_root/mounts/clusters/faisalpc/code/Users/SP19-MCS-017/content/photo_restoration/Global/t/
processing index.jpg
Traceback (most recent call last):
  File "detection.py", line 155, in <module>
    main(config)
  File "detection.py", line 117, in main
    transformed_image_PIL = data_transforms(scratch_image, config.input_size)
  File "detection.py", line 30, in data_transforms
    return img.resize((config.image_size, config.image_size), method)
AttributeError: 'Namespace' object has no attribute 'image_size'


i am running global restoration and facing this issue
