### ISSUE TITLE
Blur vs Motion-Blur on Text Image Restoration.

### ISSUE THREAD

**Issue by innat** [microsoft/Bringing-Old-Photos-Back-to-Life#57]
Hello. At first, Thanks for s sharing this amazing project. You guys have done a really good job. 

Currently, I'm going through your research paper. As you stated in the paper, the **local branch** targets the unstructured defects, such as noises and blurriness. This inspired me to try it over an ongoing problem about OCR ([here](https://stackoverflow.com/questions/64808986/scene-text-image-super-resolution-for-ocr)). Just to make a quick test, I've tried it on two cases, **gaussian blur** and **motion blur** text (with minimum acute). I've found that the model does a great job of restoring **gaussian blurry** text but not much on **motion blur**. Please see the results below, (`left-side`: normal image; `right-side`: restored image)

![two_soft](https://user-images.githubusercontent.com/17668390/100231334-0fde1080-2f51-11eb-962e-014afbdf8e1e.png)

I believe that the model has much potential to restored more complex degraded raw samples. However, I like to know, in training time, was it ensured various blurring effects in the training data set? Or, to generalize the model on various blurry effects, do we need to fine-tune it?

**Comment by zhangmozhe** [comment]
Hi, we manually synthesize some degraded images during training, which contain Gaussian blur. Also, our training involves real photos, but most of them do not suffer from motion blur. Therefore, our model currently cannot generalize to motion blur. For your case, you need to finetune the model using your training pairs.

**Comment by innat** [comment]
Hmm, I see. Have you published the training code? Or, there're still left some formalities?

**Comment by CodeMadUser** [comment]
> Hi, we manually synthesize some degraded images during training, which contain Gaussian blur. Also, our training involves real photos, but most of them do not suffer from motion blur. Therefore, our model currently cannot generalize to motion blur. For your case, you need to finetune the model using your training pairs.

hello,I am a developer working on image reconstruction. After reading the code of your old photo project of bringing-old-photos-back-to-life in detail, I got the following error while testing the code of the training part of the source code:
    when I run train_domain_B.py,it occurs error:

    Traceback (most recent call last):
    File "train_domain_B.py", line 48, in
    model = create_model(opt)
    File "D:\pythonProject\6_18\BringOldBack\Global\models\models.py", line 17, in create_model
    model.initialize(opt)
    File "D:\pythonProject\6_18\BringOldBack\Global\models\pix2pixHD_model.py", line 40, in initialize
    opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids, opt=opt)
    File "D:\pythonProject\6_18\BringOldBack\Global\models\networks.py", line 60, in define_G
    netG = GlobalGenerator_v2(input_nc, output_nc, ngf, k_size, n_downsample_global, n_blocks_global,     norm_layer, opt=opt)
    NameError: name 'GlobalGenerator_v2' is not defined

I'm looking forward to you reply.thank you.

**Comment by jobaerk** [comment]
![বাংলাদেশ-সেনাবাহিনী-নিয়োগ-২০২৪-সার্কুলার-27-12-23-1-scaled](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/assets/143795570/d9b130a3-9543-4061-b2a3-52f1db61d7c9)
