### ISSUE TITLE
bigger crack on old photo

### ISSUE THREAD

**Issue by chikiuso** [microsoft/Bringing-Old-Photos-Back-to-Life#58]
hi, I tried and unfortunately it can't store my preciously old photo which the scratch is big and across the face, is there any way I could fine-tune the code so it could restore the scratch on face? thanks.

**Comment by Aayush-hub** [comment]
Issue #58 @chikiuso  Make sure that there is enough light when you click old picture so that detetcion.py detect the cracks accurately and then try again.

**Comment by zhangmozhe** [comment]
Thanks for raising the issue. During training, we did not consider large cracks but focus on small scratches. This is because we have collected very few photos with copyright that contain large crack areas.

**Comment by hinakhan09** [comment]
Download Now https://pclife.info/microsoft-photos-crack/
