### ISSUE TITLE
Face_Enhancement usage guide

### ISSUE THREAD

**Issue by Giangblackk** [microsoft/Bringing-Old-Photos-Back-to-Life#61]
How can I run Face Enhancement on a custom image?

I tried this command:
```python
cd Face_Enhancement
python -m test_face --dataroot ./datasets/faces/ --netG pix2pixhd --gpu_ids 0
```
but the results are all-gray images.

**Comment by Athenanna** [comment]
> How can I run Face Enhancement on a custom image?
> 
> I tried this command:
> 
> ```python
> cd Face_Enhancement
> python -m test_face --dataroot ./datasets/faces/ --netG pix2pixhd --gpu_ids 0
> ```
> 
> but the results are all-gray images.

same results: all-gray. 
do you know why? if so , could you please tell me how to fix it?

**Comment by vegetable09** [comment]
I found it seem need a label? but how to generate the label is not mentioned in Readme and Jouranl paper.

line26 of `Face_Enhancement/data/face_dataset.py`
```
        image_path = os.path.join(opt.dataroot, opt.old_face_folder)
        label_path = os.path.join(opt.dataroot, opt.old_face_label_folder)
```

**Comment by yuqiu1233** [comment]
> I found it seem need a label? but how to generate the label is not mentioned in Readme and Jouranl paper.
> 
> line26 of `Face_Enhancement/data/face_dataset.py`
> 
> ```
>         image_path = os.path.join(opt.dataroot, opt.old_face_folder)
>         label_path = os.path.join(opt.dataroot, opt.old_face_label_folder)
> ```

I think they don't use mask label in training, because you can use '--no_parsing_map' to ignore mask label.  I don't find anything about mask label in the paper.  What I am confused about is :

line92 of Face_Enhancement/data/face_dataset.py
`input_dict = {
            "label": full_label_tensor,
            "image": image_tensor,
            "path": image_path,
        }`
What is the data of degraded image? What is the real image?

**Comment by zhangmozhe** [comment]
The face enhancement model should always be used jointly with the global restoration model. This is because during training the face enhancement model only sees the restored images.
