### ISSUE TITLE
i want to run it on cloud azure can any one help me to work with me

### ISSUE THREAD

**Issue by Faisalrahi1234** [microsoft/Bringing-Old-Photos-Back-to-Life#70]

**Comment by zhangmozhe** [comment]
Please refer to our Colab demo.

**Comment by phadytou** [comment]
Thank you so much

**Comment by Faisalrahi1234** [comment]
https://colab.research.google.com/drive/1NEm6AsybIiC5TwTU_4DqDkQO0nFRB-uA?usp=sharing

**Comment by Faisalrahi1234** [comment]
Gui for desktop also available if you want contact me
