### ISSUE TITLE
docker have some issue mention in screen shot i am using ainize.ai website

### ISSUE THREAD

**Issue by Faisalrahi1234** [microsoft/Bringing-Old-Photos-Back-to-Life#71]
![Screenshot_2020-12-05 microsoft Bringing-Old-Photos-Back-to-Life](https://user-images.githubusercontent.com/58216377/101260594-f445e780-3752-11eb-90e4-3c8f60d5fdf7.png)

**Comment by zhangmozhe** [comment]
We've fixed that. Please have a try.
