### ISSUE TITLE
No image created after all stage finish

### ISSUE THREAD

**Issue by lixw1021** [microsoft/Bringing-Old-Photos-Back-to-Life#73]
Environment:
- Mac OS, Big Sur
- IntelliJ 2020.2.3 IDEA CE
- python 3.7

running process shows success 

```
python3 run.py --input_folder /Users/test/Bringing-Old-Photos-Back-to-Life/image_input --output_folder /Users/test/Bringing-Old-Photos-Back-to-Life/image_out --GPU -1  

Running Stage 1: Overall restoration
Now you are processing WechatIMG496.png
Finish Stage 1 ...

Running Stage 2: Face Detection
Finish Stage 2 ...

Running Stage 3: Face Enhancement
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...

Running Stage 4: Blending
Finish Stage 4 ...

All the processing is done. Please check the results.

```

<img width="386" alt="Screen Shot 2020-12-05 at 10 49 08 PM" src="https://user-images.githubusercontent.com/24383706/101266990-17b96400-374c-11eb-87d1-44e412959188.png">

😞 no luck for me, Is there anyone run it on Mac OS successfully?

**Comment by lixw1021** [comment]
Looks like my previous image is too large, if I used the sample from the repo, it works good, 
Nice project guys!!!

**Comment by AmitSharma1127** [comment]
What's the way around to play with large images?

**Comment by Taboodaddyy** [comment]
I’m learning on iOS so I’m not sure what other then a app or reading air
and space magazine talked about the prices

**Comment by lixw1021** [comment]
> What's the way around to play with large images?

Hey, I was using a MacBook Pro, and run it without gpu, I think this maybe the reason. you can try to play it with large images on GPU machine. Hope it works

**Comment by int0x80-sys** [comment]
Hi. Same issue here. I'm trying to recover a 1627 x 1891 image (may be the resolution is too random). I suppose setting the --GPU to 0 use my vcard (is a GeForce 960).
