### ISSUE TITLE
What do you mean by "contradictory loss"?

### ISSUE THREAD

**Issue by JeremieGauthier** [microsoft/Bringing-Old-Photos-Back-to-Life#74]
In page 4 of the paper https://arxiv.org/pdf/2009.07047v1.pdf, it says the encoder ER,X of VAE1 tries to fool the discriminator with a **contradictory loss** to ensure that R and X are mapped to the same space.  What do you mean by "contradictory loss"?

**Comment by zhangmozhe** [comment]
We've fixed the default input/output directory in `run.py`. Or you can modify the arguments when running `python run.py --input_folder [test_image_folder_path]  --output_folder [output_path]  --GPU 0`
