### ISSUE TITLE
CUDA out of memory.help

### ISSUE THREAD

**Issue by luofengda** [microsoft/Bringing-Old-Photos-Back-to-Life#77]
![image](https://user-images.githubusercontent.com/10395174/101517034-31acae00-39bb-11eb-9ae7-75a8b15defd4.png)

**Comment by Artyrm** [comment]
Memory used by CUDA depends on the resolution of your photos. Hence you need to scale them down to fit in memory. CUDA says you lack mere megabytes from your total 3GB, so you can try to scale down just a bit, not loosing much resolution. If I remember correctly, resulting resolution should be x16 multiplier (i.e. 256 or 1024 px for example) for output not being stretched.

Or, you have second option: run it on Google Colab, there you'll have 16GB of memory, and surely fit there.

**Comment by franva** [comment]
@Artyrm Colab has the same issue: https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/72
and to require people to have 16GB RAM GPU,  it's not practical.

**Comment by zhangmozhe** [comment]
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416
