### ISSUE TITLE
how to introduce film grain with python

### ISSUE THREAD

**Issue by vegetable09** [microsoft/Bringing-Old-Photos-Back-to-Life#80]
![图片](https://user-images.githubusercontent.com/15920086/101714485-a32c4f80-3ad4-11eb-80f8-9ad93239137c.png)
I have no idea and found a ffmpeg film grain tutorial, but since i not familiar with ffmpeg, is it possible to introduce film grain effect with PIL or opencv?

**Comment by phadytou** [comment]
Thank you so much

**Comment by vegetable09** [comment]
@phadytou could you give some hints to realize film grain effect with Pillow or opencv

**Comment by yuqiu1233** [comment]
@vegetable09 Maybe Gaussian white noise?

**Comment by phadytou** [comment]
Thank you so much
