### ISSUE TITLE
Latent Space Dimension for the VAE_1 and the VAE_2

### ISSUE THREAD

**Issue by JeremieGauthier** [microsoft/Bringing-Old-Photos-Back-to-Life#82]
In the paper, they did not integrate what is the latent space dimension for VAE_1 and the VAE_2. So far I have tested z_dim = 256, 512, ..., 4096 with input size (3, 256, 256). 

What could be a good latent space dimension?

**Comment by zhangmozhe** [comment]
Training code is just added. Welcome to go through the training details.
