### ISSUE TITLE
Scratch removal non-optimal use of memory?

### ISSUE THREAD

**Issue by Artyrm** [microsoft/Bringing-Old-Photos-Back-to-Life#83]
I noticed that` --witch_scratch` is much more demanding for the GPU memory. I have an impression that base algorithm handles twice the resolution without "Out of memory" error.

Seems like counter-intuitive, since "scratch removal" looks like less sophisticated procedure? Am I right here, and if so, what can be done about it?

**Comment by zhangmozhe** [comment]
We are actively solving this OOM issue. The issue is duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416
