### ISSUE TITLE
I got an error when run this '--GPU -1 --with_scratch'

### ISSUE THREAD

**Issue by songkaiha** [microsoft/Bringing-Old-Photos-Back-to-Life#84]
this is my cmd 
`python run.py --input_folder sk-folder1  --output_folder sk-res --GPU -1 --with_scratch`
and got this
`Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
Traceback (most recent call last):
  File "detection.py", line 155, in <module>
    main(config)
  File "detection.py", line 80, in main
    model.to(config.GPU)
  File "/Users/max/www/python/test/Bringing-Old-Photos-Back-to-Life/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 600, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Device index must not be negative
You are using NL + Res`

and I take out this '--with_scratch',it can work.
help,please.

**Comment by handongopqwe** [comment]
I also encountered this problem :(

**Comment by songkaiha** [comment]
> I also encountered this problem :(
I guess the GPU version doesn't support scratch removal yet

**Comment by codeandmedia** [comment]
> 
> 
> > I also encountered this problem :(
> > I guess the GPU version doesn't support scratch removal yet

The same behavior, without --with-scratch it works fine

**Comment by piggy2303** [comment]
i have solution
in file Global/detection.py
you need to change some code

<img width="1093" alt="Screen Shot 2020-12-30 at 13 34 54" src="https://user-images.githubusercontent.com/33578509/103334441-df374c80-4aa3-11eb-9385-698b705b728e.png">
<img width="1093" alt="Screen Shot 2020-12-30 at 13 35 05" src="https://user-images.githubusercontent.com/33578509/103334445-e2323d00-4aa3-11eb-91b0-55cba52dd0f1.png">

```
        if config.GPU < 0:
            scratch_image = scratch_image.cpu()
        else:
            scratch_image = scratch_image.to(config.GPU)
```

```
    if config.GPU < 0:
        model.cpu()
    else:
        model.to(config.GPU)
```
