### ISSUE TITLE
googlelab: Scratch Detection.error!!!help

### ISSUE THREAD

**Issue by luofengda** [microsoft/Bringing-Old-Photos-Back-to-Life#85]
Why can't I fix the photos with traces? What needs to be done?

![a](https://user-images.githubusercontent.com/10395174/102105308-36191100-3e6a-11eb-8469-7d859a2ed037.jpg)
![a](https://user-images.githubusercontent.com/10395174/102105320-387b6b00-3e6a-11eb-8fd8-7d9206c566fa.png)

**Comment by zhangmozhe** [comment]
Can you give more information for this?
