### ISSUE TITLE
High Resolution Photos

### ISSUE THREAD

**Issue by elfsmelf** [microsoft/Bringing-Old-Photos-Back-to-Life#9]
Hi!

The code is working quite well! My only issue is for serious photo restoration it doesn't support higher resolution scans. I've been working on a workaround for this, but I was wondering if there was anything that could be done in a future iteration to help with higher resolution images?

I have split a larger photo into smaller images and then re-stitched it together. Is there anyway I can get the code to run on one large image so the color is consistent and no photo detail is lost?

I've included some examples of my workaround.
Original:
![Picture2](https://user-images.githubusercontent.com/33221917/93709841-13d26880-fb85-11ea-88b6-34b13b98946f.png)

'Stitched'
![Stitched](https://user-images.githubusercontent.com/33221917/93709879-6449c600-fb85-11ea-924d-799913cef496.jpg)

Lower resolution (full image)
![507a96fc-9b9d-4d15-b8b9-fb5f864d0efc](https://user-images.githubusercontent.com/33221917/93710600-4d0dd700-fb8b-11ea-93ac-ee4632415d72.png)

**Comment by zhangmozhe** [comment]
Hi, thanks for trying the code. This project is for research purpose and is trained on roughly 256*256 images. We will release the training code next. Probably we will retrain the network on higher resolution images to fit your usage.

**Comment by raywzy** [comment]
Well, your patch-based testing strategy is really great! One solution is that, I don't know if it will work, perhaps you could use some color matching methods like histogram matching to make the colors of different patches consistent.

**Comment by innat** [comment]
@zhangmozhe Just to add with @elfsmelf 

If you notice the above image example, some scratches are passed over the mouth (the guy on the left side). And when It's restored by the proposed method, it does really well overall, however, it doesn't preserve mouth information there. It may also happen some other very essential parts in the image, for humans, it can be eyes, nose, etc. 

And another thing, maybe good to add some mechanism to [colorize ](https://github.com/ericsujw/InstColorization) the black and white image, totally optional though :joy:

**Comment by davaram** [comment]
> Hi!
> 
> The code is working quite well! My only issue is for serious photo restoration it doesn't support higher resolution scans. I've been working on a workaround for this, but I was wondering if there was anything that could be done in a future iteration to help with higher resolution images?
> 
> I have split a larger photo into smaller images and then re-stitched it together. Is there anyway I can get the code to run on one large image so the color is consistent and no photo detail is lost?
> 
> I've included some examples of my workaround. Original: ![Picture2](https://user-images.githubusercontent.com/33221917/93709841-13d26880-fb85-11ea-88b6-34b13b98946f.png)
> 
> 'Stitched' ![Stitched](https://user-images.githubusercontent.com/33221917/93709879-6449c600-fb85-11ea-924d-799913cef496.jpg)
> 
> Lower resolution (full image) ![507a96fc-9b9d-4d15-b8b9-fb5f864d0efc](https://user-images.githubusercontent.com/33221917/93710600-4d0dd700-fb8b-11ea-93ac-ee4632415d72.png)

Very good idea. After trying it, I found that the cropped picture was scratched and merged, and there was a chromatic aberration.How to remove it?

**Comment by hinakhan09** [comment]
Download Now https://pclife.info/microsoft-photos-crack/
