### ISSUE TITLE
Inconsistency between code and paper

### ISSUE THREAD

**Issue by NK-CS-ZZL** [microsoft/Bringing-Old-Photos-Back-to-Life#91]
In the paper, VAE is used to transform images into latent code. However, when I see released testing code. It seems that there are just ordinary AEs(auto encoder) which transform images into feature maps rather than probability distribution.

To my best knowledge, VAE is used to estimate distributions(specifically means and variances). What we get  from VAE encoder should be a group of means and variances. Then we sample from a N(0, 1) and input of VAE decoder is z = σx+μ(δ: standard deviation, μ: mean), namely reparameterization trick in paper. But I can't find such operations in code.

I also see pseudo training code in #81 and his VAE conducts sampling operation in training phase but directly feed outputs of encoder without sampling in testing phase. In #29 , @zhangmozhe said there is no need to do the reparameterization trick. However, aforementioned comments differ from implementation of VAE in [PyTorch-VAE](https://github.com/AntixK/PyTorch-VAE/blob/master/models/vanilla_vae.py) in which VAE conduct same operation in training and testing.

 So my questions are:
- Why is there not sampling operation in testing code?
- Is my description of VAE correct? If not, please rectify it.
- Is there using a new type of VAE which is diverse from vanilla one? If so, could you give me some related papers?

**Comment by Jak0917377107** [comment]
เมื่อ พ. 16 ธ.ค. 2563 เวลา 14:30 NK-CS-ZZL <notifications@github.com>
เขียนว่า:

**Comment by zhangmozhe** [comment]
During training, VAE is a must for achieving high-performance quality, which introduces perturbation to the latent space so that the sampling from this continuous space can be mapped to an image. During inference, there is not need to introduce such perturbation, so we just use the centroid of the latent space from which we reconstruct the image. Therefore, the code looks like an autoencoder.
