### ISSUE TITLE
About VAE1 loss third term L_VAE1,GAN(r)

### ISSUE THREAD

**Issue by Star-Stone** [microsoft/Bringing-Old-Photos-Back-to-Life#99]
What is VAE loss third term L_VAE1,GAN(r)？
![](https://i.loli.net/2020/12/23/XUl1buZSr4259iI.jpg)
And what is difference between L_VAE1,GAN(r) and L^latent_VAE1,GAN(r, x)?
![](https://i.loli.net/2020/12/23/aGwNMv29K3bJHZc.jpg)

**Comment by zhangmozhe** [comment]
Hi, these are two distinct discriminators. One is use examine the realism of the reconstructed image, while another is to examine the gap between synthetic image and real photo in the latent space.

**Comment by Star-Stone** [comment]
Thank you!
